### ISSUE TITLE
Easily search for terms in target system

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#100]
To find a corresponding concept from the target system, users will want to search for terms related to the source concept in the target system. These terms would be for example in the notes, GND terms, or alternative labels/register entries. We could add a small tooltip that pops up when a user selects text inside of ItemDetail the allows them to search for the selected text in the target system.

Example workflow:
- Select concept in source system.
- Click on GND terms.
- Select a term either by normal text selection or double clicking on a term.
- A small magnifying glass pops up, click on that.
- The term will be inserted in the target system search field and it will show the results.

Related links for implementation:
- https://erdembircan.github.io/selection-popup/
- https://stackoverflow.com/questions/5517260/how-to-have-a-popup-after-selecting-text

**Comment by nichtich** [comment]
Same for terms from register entries. It might also be provided by an icon that is only shown when hovering the terms.

**Comment by nichtich** [comment]
See also #84.

**Comment by stefandesu** [comment]
A very simple implementation of this would be to automatically insert the prefLabel of the left concept into the search field on the right side.

An extensions would be to search for the concept's labels in the target system and show the results as mapping recommendations in MappingBrowser. This would be kind of a first step towards #84.

Depends on #168 to be finished.

**Comment by nichtich** [comment]
Label should also be inserted when scheme is switched.

**Comment by stefandesu** [comment]
> Label should also be inserted when scheme is switched.

Do you mean that the label of the right side should be inserted in the search field on the left side? 

Also, when are we considering this issue to be done? I don't think I would show the search results as mapping recommendations and rather go directly to OpenRefine (#84).
