### ISSUE TITLE
MappingEditor: remove information and buttons from the bottom

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#113]
Simplify visual layout of MappingEditor by removal of

* messages such as "Selected concept is already in mapping"
* The big trash bin icon to delete all concepts
* The big plus icon to add selected concept

**Comment by stefandesu** [comment]
I have the feeling that the plus icon would still be very handy (I personally use it a lot when testing, and I never use the other buttons for adding a concept to a mapping), but we could remove those things and see if it comes up in the testing phase.

**Comment by nichtich** [comment]
At least remove the message "Please select a concept"/"Selected concept is already in mapping"/...

We can try to move the buttons to the top so it's more like a toolbar/header.

**Comment by stefandesu** [comment]
> At least remove the message "Please select a concept"/"Selected concept is already in mapping"/...

Sure! 

> We can try to move the buttons to the top so it's more like a toolbar/header.

Yeah, we can try out different ideas and see what might be best. 👍

**Comment by stefandesu** [comment]
I removed all buttons for now. I admit it definitely looks way cleaner. I guess if there is a need for a "add to mapping" button there, it will come up during testing again.
