### ISSUE TITLE
Highlight mapping currently shown in MappingEditor?

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#116]
If two concepts A and B are selected on the left and on the right, this mapping A to B is also highlighted in the MappingBrowser (and in the OccurrencesBrowser when #73 is implemented).

If the MappingEditor includes two concepts X and Y, it should also be visible whether this mapping exists (MappingBrowser) and what Occurrences of this mapping exist (OccurrencesBrowser). This is tricky because A and B may be equal to X and Y or they may be different.

**Comment by stefandesu** [comment]
We would need different highlight colors for different scenarios:

1. Concepts of mapping are selected on the left and right.
2. Concepts are part of the mapping in MappingEditor.
3. Mapping is hovered somewhere else.

And combinations of those. The question here is also whether 1. should even be highlighted (#73 originally suggests to remove that highlight).

**Comment by nichtich** [comment]
This also overlaps with #115. It's complicated and I'll move this to milestone 1.0.0.

**Comment by stefandesu** [comment]
#115 has been implemented and I wonder whether this issue here is still relevant. If we introduce even more ways of highlighting mappings, it will be difficult to understand the meaning behind it. I would maybe suggest to implement #73 instead (should be pretty simple) and close this issue.

**Comment by stefandesu** [comment]
Depends on #231.

**Comment by stefandesu** [comment]
This issue is very related to #343. Here, we are discussing if and how a mapping A->B in Mapping Editor is highlighted in Mapping Browser. But if neither A or B are currently selected, the mapping A->B will not even show up in Mapping Browser, at least not in Mapping Navigator.

1. Should this even be implemented at all?
2. If yes, how should mappings be highlighted, and should they be highlighted in both Mapping Search, and Mapping Navigator?
3. How do we deal with the fact that with the current logic of Mapping Navigator, the mapping might not even show up?

**Comment by nichtich** [comment]
Too many kinds of highlighting would be complicated. By now we have:

1. mapping currently being edited (linked by its URI), internally by an object reference
2. when left and right selected concepts match a mapping's members (should be based on `urn:jskos:mapping:members:` but is currently not)

This issue is about adding 3. highlighting if `urn:jskos:mapping:content:` id match. 

Case 2 and 3 should get same color.

**Comment by stefandesu** [comment]
I accidentally implemented it a little bit different now:

1. The mapping currently being edited is identified by its URI and highlighted in the same yellow highlight color as the selected concepts in MappingBrowser.
2. If selected concepts on the left and right match the concepts in the mapping (using `urn:jskos:mapping:members:` identifier), the mapping will be highlighted in the same blue color as before.
3. If the current mapping in MappingEditor has the same members (again, using `urn:jskos:mapping:members:`), the mapping will be highlighted as well (same color as in (2)).

(1) Takes precedence over the others. The difference to your comment is that I've used the members for (3) as well. Is that okay or should we better use the content identifier?

**Comment by stefandesu** [comment]
Hover colors should be adjusted depending on the highlight color. After that, this issue can be closed.
