### ISSUE TITLE
MappingBrowser and OccurrencesBrowser: hide table header

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#119]
Showing table headers does not make sense if tables are empty ("No mappings available"/"No occurrences found")

**Comment by stefandesu** [comment]
We might have had this conversation before, but I think it looks so much better and way more consistent if we keep the table header there at all times. I also think a table header does make sense even if there are (currently) no items in the table. If it's just "No mappings available" in the component, it looks very empty and in my eyes kind of wrong.

Current behavior:

![kapture 2018-08-15 at 11 26 51](https://user-images.githubusercontent.com/3275148/44141730-474fbbcc-a07e-11e8-9293-86b7ef154609.gif)

Suggested behavior (hiding table header):

![kapture 2018-08-15 at 11 25 10](https://user-images.githubusercontent.com/3275148/44141752-5f95c014-a07e-11e8-992d-d9418eed38f9.gif)

**Comment by nichtich** [comment]
I've cleaned up the table header by removal of some headings, so it looks less heavy. Thanks for the comparision, we better keep it this way.
