### ISSUE TITLE
Add normal links in quick selection

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#128]
Related to https://github.com/gbv/cocoda/issues/13#issuecomment-416048866: the quick selection links should also be normal links with URL parameters `schemeLeft`, `schemeRight`, `mapping`, so the links can be shared and opened in a new tab if wanted.

**Comment by stefandesu** [comment]
We could even turn concept selection links into normal links with URL parameters and let the application handle the changes. 

Only think to consider is that, yes the links could be shared and opened in a new tab, but they would still include the rest of the state (mapping, other selected scheme/concept).

**Comment by stefandesu** [comment]
All concepts and schemes that are selectable are now normal links.
