### ISSUE TITLE
MappingBrowser: make all concepts selectable

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#129]
Select sample concept DDC 612.112 and select scheme BK at the right. In the mapping browser RVK concepts such as WW 8844 cannot be selected because they are not part of BK. Better make all concepts selectable and switch concept scheme if needed. It's easy to go back via history.

**Comment by stefandesu** [comment]
I agree, that was a decision from the beginning where we did not have the history and is now irrelevant.

**Comment by stefandesu** [comment]
This is now in dev. I applied the logic you described in [this comment](
https://github.com/gbv/cocoda/issues/118#issuecomment-416556629) (with small adjustments). Please test if it feels right before we close the issue.
