### ISSUE TITLE
Unify URL parameters with jskos-server

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#130]
See https://github.com/gbv/jskos-server#mappings:

* `fromScheme` and `toScheme` instead of `schemeLeft` and `schemeRight`
* `identifier` instead of `mappingId`

**Comment by stefandesu** [comment]
And `from` and `to` instead of `conceptLeft` and `conceptRight`, right?

**Comment by stefandesu** [comment]
Now implemented. Obviously links with the old parameters will not work anymore.
