### ISSUE TITLE
fa-share icon is hidden by AdBlock Plus

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#132]
[Adblock Plus hides the fa-share icon](https://help.getadblock.com/support/solutions/articles/6000148708-adblock-blocks-font-awesome-social-media-icons) used in MappingApp. A workaround (other than disabling AdBlock for the site) is to replace the CSS class name `fa-share` with `fa-share-alt` or some other custom name.

**Comment by stefandesu** [comment]
I replaced the icons with different ones. I wasn't sure how to rename the CSS class names if we're using the Vue plugin for FontAwesome, so this was the easier solution. 

I tested it with AdBlock Plus and both the "Fanboy's Social Blocking List" and "Fanboy's Annoyance List".
