### ISSUE TITLE
MappingBrowser: Extend mapping schemes with known notation

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#136]
With <https://github.com/gbv/cocoda/commit/cdd21dca11a08d1e51f6f3f1a2b512c7d069f471> mappings retrieved via mapping providers don't need to include a scheme notation such as "RVK". Cocoda should infer the notation from known concept scheme URI.

**Comment by stefandesu** [comment]
When a concept is added to the Vuex store, the "inScheme" property already gets replaced with the object reference for the concept scheme that's already in the Vuex store (if there is one). So to fix this issue, we'd only have to add all concepts from mappings to the Vuex store.

It would be good to have an example where this is the case.

**Comment by stefandesu** [comment]
My previous comment was basically irrelevant because we're not using the concepts' `inScheme` property but rather `fromScheme` and `toScheme` of the mapping. I implemented this issue accordingly.
