### ISSUE TITLE
New component: ConceptList

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#139]
To show a list of concepts alternatively to ConceptTree. Use for:

* list of concepts not mapped yet (left)
* list of recommended concepts to map currently selected concept to (right), e.g. mapping recommendations retrieved via reconciliation API

**Comment by stefandesu** [comment]
Is this different from looping over concepts and displaying them via ItemName, similar to how ancestors and children are displayed in ItemDetail? Not sure if a component is really necessary.

Or do you mean this should be an actual top level component alongside ItemDetail and ConceptTree? Won't this become way to cluttered and tight? The application is already super crowded.

**Comment by nichtich** [comment]
We probably need different modes to enable/disbable/show/hide components. This issue might better be split because it covers two use cases (list of unmapped concepts and list of recommended concepts to map to). I don't know where/when to show (maybe instead of ConceptTree) but this is a question of workflows.

**Comment by nichtich** [comment]
We could also support custom concept list(s). Users could fill this lists with queries (e.g. give me all concepts from subtree X of concept scheme Y which have no mappings to concept scheme Z) and process this lists. An indicator could show whether a concept is in the list(s). If one list is enough this could be called bookmarks.

**Comment by nichtich** [comment]
In addition to showing the full list, the ConceptDetail component could have a previous/next button to navigate trough a list of concepts, for instance for review

**Comment by stefandesu** [comment]
If used, this component could be shown instead of the ConceptTree.

**Comment by stefandesu** [comment]
I could imagine implementing this earlier than 1.0.0, but it depends on how prioritize issues.

**Comment by stefandesu** [comment]
I just noticed that ConceptTree and ConceptTreeItem are basically nothing else than a ConceptList and ConceptListItem, except that instead of hardcoding it to use top concepts, the concepts are provided through a property.

I would then add a wrapper component that allows switching between showing the top concepts and other lists (currently only favorite concepts).

**Comment by stefandesu** [comment]
It's now possible to choose between the tree and favorite concepts. Some additional work is necessary though:

- [x] Fix issue when no tree is available
- [x] Fix overflow issue
- [x] Improve appearance of choice selection (currently a simple button dropdown) -> implement better tabs (#418)
- [x] Add localization
- [x] Remove old remnants of "ConceptTree"
- [x] Create new issue for more lists
- [x] Question: Should choice selection persist when changing concept scheme?
- [x] Force concepts to be opened on the correct side (now that there can be concepts from multiple schemes)
- [x] Add option to show schemes in front of concepts
