### ISSUE TITLE
Hide already chosen schema on other side

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#14]
In other words, prevent choosing the same schema on both sides.

**Comment by nichtich** [comment]
I'm not sure whether this is actually needed. Moreover there might be use cases of mapping one system with concepts from itself. In DDC we have [Synthesized number components](https://github.com/gbv/mc2skos#synthesized-number- components) - these are not actual mappings but have similar semantics.

**Comment by stefandesu** [comment]
Closed for now as it doesn't seem to be necessary.
