### ISSUE TITLE
Move quick selection placeholder to scheme selector

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#141]
The quick selection of schemes and sample concepts should better be shown as part of the `schemeSelectWrapper` instead of the `conceptBrowser`. The latter should not be shown if no concept scheme is selected.

**Comment by stefandesu** [comment]
While the quick selection is not part of `schemeSelectWrapper` now, I moved it below `schemeSelectWrapper` and therefore outside of `conceptBrowser`.
