### ISSUE TITLE
MappingApp: Extend table of concordances

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#144]
* [ ] hide description, creator, and download column if screen width too small (see [boostrap responsive](https://getbootstrap.com/docs/4.0/utilities/display/#hiding-elements))
* [ ] add column with date (field `modified` or `created`)
* [ ] allow filtering by from/to/creator

The latter may better be and independent issue: add input fields at the table bottom row (?) to select from, to, and creator. The total number of mappings should be calculated dynamically so users can quickly find out for instance the number of concordances and mappings from RVK.

**Comment by stefandesu** [comment]
This is now implemented, except for hiding certain columns on smaller screens because that would require complicated changes in vue-flexible-table. I will open an issue there which would allow this to work and close this issue here.
