### ISSUE TITLE
Allow saving mappings from mapping database to local store

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#145]
Existing mappings opened from the mapping database (those with an URI) cannot be saved to local storage - this is only possible if a mapping is newly created by hand. Saving should be changed to always act on a selected storage backend (by now: local storage) independent where mappings have been loaded from. The `creator` field should be kept and only overridden when the mapping is modified.

**Comment by stefandesu** [comment]
This is not completely correct. Existing mappings opened from the mapping database can be saved to local storage **if they were modified**. Does it really make sense to have the exact same mapping in both the mapping database and local storage? Changing this would also affect other things:

- We would need to display duplicate mappings in MappingBrowser (right now, they are filtered out and only one is displayed).
- It would mess with the workflow that the save button is only activated if the mapping was changed.

I personally would (for now) keep the current behavior.

**Comment by stefandesu** [comment]
There is actually a way to save an existing mapping in local storage:

- edit an existing mapping
- change its type
- save (will be saved to local storage)
- change the type back to the original
- save again

But due to filtering duplicate mappings, it will not be shown in the list anyway. The only way to then delete the mapping is to modify and save it once again so that it will be shown in the list. This doesn't seem to be great behavior either.

What do you think?

**Comment by nichtich** [comment]
Looks like filtering duplicate mappings should be disabled then

**Comment by stefandesu** [comment]
> Looks like filtering duplicate mappings should be disabled then

Yes, I guess so. Also, I would show local mappings on the top by default (if no column is chosen for sorting). Right now, they'll just show up at seemingly random places.

**Comment by stefandesu** [comment]
Due to the refactor of MappingBrowser and OccurrencesBrowser (#147), I would postpone this issue until after that is done. It'll probably come up during the refactor anyway and might be fixed as a result.

**Comment by stefandesu** [comment]
The changes in https://github.com/gbv/cocoda/commit/a406f0a3f87ef91aeedd5ff8fb826b2b61c9977a now allow saving of existing mappings in local storage. Before closing this issue, I would add a "save mapping" button behind all non-local mappings/suggestions to save them into local storage.
