### ISSUE TITLE
Ambiguous BARTOC URI for BK

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#146]
http://bartoc.org/en/node/745 and http://bartoc.org/en/node/18785

See [this example](https://gbv.github.io/cocoda/dev/?toScheme=http%3A%2F%2Furi.gbv.de%2Fterminology%2Frvk%2F&to=http%3A%2F%2Frvk.uni-regensburg.de%2Fnt%2FWW_8840&from=&fromScheme=http%3A%2F%2Fdewey.info%2Fscheme%2Fedition%2Fe23%2F). In the occurrences, there are two co-occurrences with BK concepts, but they could not be matched to the right concept scheme because there are no overlapping URIs. DANTE uses http://bartoc.org/en/node/18785, but the occurrences API returns http://bartoc.org/en/node/745.

This might be correct behavior because one refers to the German version of the classification and the other to the Dutch one.

**Comment by nichtich** [comment]
Fixed by updating occurrences-api
