### ISSUE TITLE
Refactor MappingBrowser and OccurrencesBrowser into one

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#147]
As discussed we better need one joint component to show mappings and mapping recommendations from multiple sources. This component should allow good filtering and/or selection of sources. Possible sources so far:

* mapping database
* occurrences api (catalogs)
* mapping recommendations via searching labels and index terms
* mapping recommendations from cc mapper
* mapping recommendations via indirect mappings from Wikidata (as linking hub)
* ...

Some sources can further be configured

**Comment by stefandesu** [comment]
With https://github.com/gbv/cocoda/commit/a406f0a3f87ef91aeedd5ff8fb826b2b61c9977a, a proposal for this issue is now in dev. It should have the same functionality as the other two components before, except for the options in MappingBrowser. Performance is currently pretty bad because occurrences are reloaded for every refresh and those queries take quite long.

**Comment by stefandesu** [comment]
Any suggestions for an appropriate name for the component? Currently, it is `SuggestionBrowser`, but it goes not only contain suggestions, also mappings.

**Comment by nichtich** [comment]
It can be kept as "MappingBrowser"

Am 5. Oktober 2018 14:21:32 MESZ schrieb Stefan Peters <notifications@github.com>:
>Any suggestions for an appropriate name for the component? Currently,
>it is `SuggestionBrowser`, but it goes not only contain suggestions,
>also mappings. 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gbv/cocoda/issues/147#issuecomment-427346392

-- 
Jakob Voß via Android

**Comment by stefandesu** [comment]
> It can be kept as "MappingBrowser"

Okay, that's good. I will delete the old MappingBrowser and OccurrencesBrowser and rename `SuggestionBrowser` to `MappingBrowser`.

**Comment by nichtich** [comment]
Documentation needs to be updated before closing this issue.

**Comment by stefandesu** [comment]
> Documentation needs to be updated before closing this issue.

Good point, will do.

**Comment by stefandesu** [comment]
Documentation updated, closing the issue now. I'd like to clarify issue #151 before creating a 0.5.0 release though.
