### ISSUE TITLE
MappingBrowser: combine same mappings into one row

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#150]
See for instance [this example](https://gbv.github.io/cocoda/dev/?fromScheme=http%3A%2F%2Fdewey.info%2Fscheme%2Fedition%2Fe23%2F&toScheme=http%3A%2F%2Furi.gbv.de%2Fterminology%2Frvk%2F&from=http%3A%2F%2Fdewey.info%2Fclass%2F512.482%2Fe23%2F&to=http%3A%2F%2Frvk.uni-regensburg.de%2Fnt%2FSK_340&mapping=%7B%22from%22%3A%7B%22memberSet%22%3A%5B%7B%22uri%22%3A%22http%3A%2F%2Fdewey.info%2Fclass%2F512.482%2Fe23%2F%22,%22notation%22%3A%5B%22512.482%22%5D%7D%5D%7D,%22to%22%3A%7B%22memberSet%22%3A%5B%7B%22uri%22%3A%22http%3A%2F%2Frvk.uni-regensburg.de%2Fnt%2FSK_340%22,%22notation%22%3A%5B%22SK%20340%22%5D%7D%5D%7D,%22fromScheme%22%3A%7B%22uri%22%3A%22http%3A%2F%2Fdewey.info%2Fscheme%2Fedition%2Fe23%2F%22,%22notation%22%3A%5B%22DDC%22%5D%7D,%22toScheme%22%3A%7B%22uri%22%3A%22http%3A%2F%2Furi.gbv.de%2Fterminology%2Frvk%2F%22,%22notation%22%3A%5B%22RVK%22%5D%7D,%22creator%22%3A%5B%7B%22prefLabel%22%3A%7B%22de%22%3A%22GVK%20-%20Gemeinsamer%20Verbundkatalog%22,%22en%22%3A%22GVK%20-%20GBV%20Union%20Catalogue%22%7D,%22uri%22%3A%22http%3A%2F%2Furi.gbv.de%2Fdatabase%2Fgvk%22%7D%5D,%22type%22%3A%5B%22http%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23mappingRelation%22%5D%7D&identifier=urn%3Ajskos%3Amapping%3Acontent%3A7eca562af42da2780acffd877c6b443eef23af97) and click on "save and edit" one of the highlighted mappings (DDC 512.482 -> RVK SK 340). This mapping then occurs three times. We could combine these three rows with the differing sources combined.

**Comment by stefandesu** [comment]
This makes a lot of sense. How should the source be displayed?

Also, there might be issues related to truncating the results, see #151.

**Comment by stefandesu** [comment]
Another question: What does "same mapping" mean in this case? Same mapping content identifier, i.e. same members and type?

**Comment by nichtich** [comment]
Mappings with same mapping content identifier could be merged (creator is repeatable) but date and uri cannot be merged so maybe only merge in the display, not internally?

**Comment by stefandesu** [comment]
Does this still apply? With the new provider system, I think it would be confusing to merge them. Also, showing information about a single mapping (#201) wouldn't make much sense (or we would need tabs for each source when showing the info).

**Comment by nichtich** [comment]
Does not fully make sense with the new provider system, so closing this.
