### ISSUE TITLE
Question: How to properly deal with truncated results in MappingBrowser?

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#151]
With the refactoring of MappingBrowser, mappings/suggestions from multiple sources are now shown in one table. To keep it simpler, not all results from the server or catalog are shown by default (currently only 5). As a way to show more of those results, I added small separators with a "show more" button (3903a71bead66dc1076787259a483b36161decd6). That works pretty well as long as the user doesn't sort the list. With sorting, mappings from the same source aren't necessarily below each other, causing the "show more" buttons to not make any sense anymore. But hiding them in the case of sorting won't make it clear that there are more results that are not currently shown. Any idea how to properly deal with this? @nichtich

**Comment by stefandesu** [comment]
A short discussion yielded the following result: Custom sorting might not even be necessary, so we could remove it for now. Instead, we sort the mappings in each group (local, server, catalog) with fixed sorting, for example like this:

- Local and server: mappings that contain both selected concepts first, then mappings containing the left concept on the `from` side, then mappings containing the right concept on the `to` side, then the rest of the mappings.
- Catalog: Always sort by occurrences descending.

If at some point we need to reintroduce sorting, we could also sort each group within itself without mixing the mappings.

- [x] Remove custom sort.
- [x] Add fixed sorting depending on the group.

Two more ideas to improve MappingBrowser were:

- [x] Add small separator between the groups.
- [x] Put the source in a separat narrow column with one letter instead of showing it together with the creator.

**Comment by nichtich** [comment]
We could just disable manual sorting and hard-code a default order instead.

Am 9. Oktober 2018 10:41:18 MESZ schrieb Stefan Peters <notifications@github.com>:
>With the refactoring of MappingBrowser, mappings/suggestions from
>multiple sources are now shown in one table. To keep it simpler, not
>all results from the server or catalog are shown by default (currently
>only 5). As a way to show more of those results, I added small
>separators with a "show more" button
>(3903a71bead66dc1076787259a483b36161decd6). That works pretty well as
>long as the user doesn't sort the list. With sorting, mappings from the
>same source aren't necessarily below each other, causing the "show
>more" buttons to not make any sense anymore. But hiding them in the
>case of sorting won't make it clear that there are more results that
>are not currently shown. Any idea how to properly deal with this?
>@nichtich 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/gbv/cocoda/issues/151

-- 
Jakob Voß via Android

**Comment by stefandesu** [comment]
> We could just disable manual sorting and hard-code a default order instead.

That was already implemented at the time of your reply. ;) I'll add the other two things above before closing this issue.
