### ISSUE TITLE
Redesign concept scheme selection

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#155]
The native dropdown of concept schemes looks different among browsers and operating systems and is limited especially for long lists. Better redesign as ConceptSchemeBrowser with 

* a full list of all schemes
* allow filtering the list via an input field (filter while typing)
* add a row with a clickable star to bookmark favorite schemes and sort bookmarked schemes at the top

The component could later be extended with additional information such as type (not included in DANTE yet), publisher, mapping coverage etc.

**Comment by nichtich** [comment]
DANTE now also returns languages of a vocabulary so vocabularies could also be filtered by language.

**Comment by stefandesu** [comment]
I implemented a first version of a redesigned scheme selection with the latest commit. There is still some cleanup necessary (particularly in `App.vue`), and the code of the new component should be better documented. Also, while favorite schemes are shown with a star already, the star is not clickable yet.
