### ISSUE TITLE
Rethink ways to prevent conflicting API requests

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#16]
All API requests are made asynchronously. Consequently, we can't be sure that calls will be finished in the same order as they are made. Therefore, it is possible that a user action overrides a call that is not yet finished and if the previous call is then slower than the new call, there might be a conflict. 

Right now, there are two solutions used in the codebase:
1. [axios cancel tokens](https://github.com/axios/axios#cancellation). Whenever a user action causes a new API call, the old call for the same action is canceled using the current cancel token and a new cancel token is created. This seems to be the "right" solution, but we need to keep track of both the cancel token and a boolean for the loading status. 
2. Save the current state that's relevant for that specific call into a local variable and check it again when the call is completed. If they are different, discard that call's data.

Suggestion: Use 1. for all calls where conflicts might occur (possibly in all API calls?). Keeping track of the loading status might be necessary anyway to show the loading indicators in the right places.

**Comment by noerrornowork** [comment]
already solved?

**Comment by stefandesu** [comment]
> already solved?

Nope, it's not a priority at the moment, but we will likely use option 1 as a solution.

**Comment by stefandesu** [comment]
When selecting a concept, conflicts are now prevented by generating IDs for each call and side. For the actual API requests, this should not be necessary anymore because all requests directly integrate the loaded information into the correct object, meaning that the loaded data won't be "lost". Therefore, I will consider this issue closed.
