### ISSUE TITLE
Link to concept sources

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#165]
E.g. DANTE https://dante.gbv.de/detail/4190026 and GND. Required if concept URIs don't point to the concept provider. Might simple be implemented in the backend?

**Comment by stefandesu** [comment]
I also think this would be better suited for the back end, otherwise we'd need to create rules in the front end for every single vocabulary on how to generate the URL. It would be best to just get a property `url` from the back end that contains that information, right?

**Comment by nichtich** [comment]
A link to the JSKOS source as retrieved by the provider is enough. This is currently implemented via hidden link for concepts but not for concept schemes, e.g. <https://gbv.github.io/cocoda/dev/?fromScheme=http%3A%2F%2Furi.gbv.de%2Fterminology%2Fgender%2F> should include a link to <http://api.dante.gbv.de/voc/gender> (or alias query with same result)

**Comment by stefandesu** [comment]
Two issues:
1. jskos-server currently can't return infos for a specific concept scheme (but this is quickly implemented).
2. What should we do with hardcoded schemes, like Wikidata or GND? There currently is no API request to return info about these schemes.

**Comment by nichtich** [comment]
If there is no API request then show the hard-coded JSON data with the "Export Mapping" modal. This should be a component of its own anyway (#230).

The link should not be hidden but a small symbol such as `{}` in the corner or title bar of a component. This also applies to MappingBrowser (instead of download in the settings) and MappingEditor (instead of export icon).

**Comment by nichtich** [comment]
This can be closed as we now have a data view with optional link to the backend. If the backend acts as wrapper, it should first include provenance information in JSKOS which can then be shown in Cocoda.
