### ISSUE TITLE
Provide GitHub releases

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#169]
As zip files to drop on a server. Requires #49.

**Comment by stefandesu** [comment]
https://docs.travis-ci.com/user/deployment/releases/

**Comment by nichtich** [comment]
The documentation should show how to try out a release with a local web server, including a simple node server such as [http-server](https://www.npmjs.com/package/http-server).

**Comment by stefandesu** [comment]
I added this to Travis now, but I wouldn't bet on it working (although it theoretically should). We'll see with the next release.

**Comment by stefandesu** [comment]
It worked: https://github.com/gbv/cocoda/releases/tag/0.9.2
