### ISSUE TITLE
Provide automatic API documentation

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#17]
A vue API documentation tool such as [vue-styleguidist](https://github.com/vue-styleguidist/vue-styleguidist) should be used to document all components.

**Comment by stefandesu** [comment]
This is now on the branch styleguidist, see ae1c0e4941c8f192b0500620971d10a1c2892888.

**Comment by nichtich** [comment]
This could be deployed automatically via travis as described at https://gist.github.com/domenic/ec8b0fc8ab45f39403dd or https://docs.travis-ci.com/user/deployment/pages/. We'll leave this ticket open until then,

**Comment by stefandesu** [comment]
Documentation is now available at https://gbv.github.io/cocoda/.
