### ISSUE TITLE
Differentiate Concept Scheme Types

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#171]
Concept Schemes can have types such as classification, thesaurus, authority file... Related to #155 we should include this type information in Terminology Providers for:

* Filtering Concept Scheme by type for selection
* Changing the view of ConceptDetail and other components (e.g. whether to use the caption "Register Entries")

See also the current KOS Registry <http://coli-conc.gbv.de/terminologies/> which should be replaced in the long run anyway.

**Comment by nichtich** [comment]
We further have concept schemes without access to concepts (see https://github.com/gbv/jskos-server/issues/49). When all of [kos-registry](https://github.com/gbv/kos-registry) have been imported into jskos-server instance, the concept scheme selection should allow filtering by:

* languages
* concept scheme types (including "other" for unknown type)
* concept schemes with access to concepts

One goal is to replace http://localhost/coli-conc.gbv.de/terminologies/

**Comment by stefandesu** [comment]
Concept scheme type filters are now fully implemented, so I'm closing this issue. Please create a new issue for the related things if necessary.
