### ISSUE TITLE
Split settings into tabs

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#173]
Split Cocoda Settings screen with tabs:

* Layout (Display Settings)
* Data Sources (currently hard-coded in config file, tab could just show a JSON object with `*Providers` fields of current configuration)
* Local Mappings
* About (Version, Build Date, license, link to sources...)

Include a note that local settings are only stored in the browser

**Comment by nichtich** [comment]
Also remove configuration key `githubUrl` and add a hard-coded link to GitHub from the settings.

**Comment by stefandesu** [comment]
Settings were now split up and reorganized. This can be further improved and extended in the future, but this issue is done now.
