### ISSUE TITLE
MappingBrowser: Show more/less information depending on the space

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#180]
If there is enough space in MappingBrowser, the concept's labels should also be shown. This probably requires adjustment in [vue-flexible-table](https://github.com/stefandesu/vue-flexible-table).

**Comment by nichtich** [comment]
Yes, labels should be shown (on column from/to) if space is available, especially if notations correspond to numeric record identifiers rather than recognizable class numbers.

**Comment by nichtich** [comment]
The "creator" column might also be hideable and show metadata (creator, created, identifier...) on hover or click (modal) of an info icon instead. The creator column is only useful in some settings, e.g. if only browsing Local and Wikidata mappings it is irrelevant.

**Comment by stefandesu** [comment]
Labels are now shown when MappingBrowser has at least 700px available, creator is only shown with at least 800px. I would suggest to always show the info icon because there is often more information available than can fit into the table.

I'm leaving this issue open until the info icon was added.

**Comment by nichtich** [comment]
I'd not center-align laben and merge notation and label into one column to be shown directly next to each other independent from width of notation. Then close this issue and create another for the info-icon-shows-mapping-metadata idea.

**Comment by stefandesu** [comment]
I made a conscious decision to have a separate column for the labels, but I found a better way to do it and it should be exactly as you want it now.
