### ISSUE TITLE
Provide additional information about Mapping Providers

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#184]
Mapping Providers can only be labeled by a short name (e.g. "Registry" or "R"), this is misleading. More information about sources of mappings should be shown e.g.

* long name ("Concordance Registry")
* description ("Mappings in the Concordance Registry have been selected by ...")
* URL to info/homepage of the provider
* ...

**Comment by stefandesu** [comment]
I just noticed that we basically have this now in settings. But maybe we should add a homepage URL as well, currently there are only our internal URIs.
