### ISSUE TITLE
Support compound mappings in CSV export

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#185]
When a memberSet has multiple members, add columns such as `toNotation2`, `toNotation3`...

**Comment by stefandesu** [comment]
Most of the logic is in [jskos-tools](https://github.com/gbv/jskos-tools/issues/6), but we can leave this open because the changes there will caused small changes in Cocoda as well.

**Comment by stefandesu** [comment]
This is now supported in jskos-tools 1.0.0 and can be implemented here.
