### ISSUE TITLE
Make build pathes relative

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#19]
The application is build and deployed at http://esx-89.gbv.de:89/, also available via reverse Proxy at http://coli-conc.gbv.de/cocoda2/. The latter does not work because build `dist/index.html` contains absolute links (starting with `/`) instead of relative links (e.g. starting with `./`). This can hopefully be configured in the vue build process.

**Comment by stefandesu** [comment]
FYI: 36e7637404b132f3cd5480ebc69446ca1a7913be actually broke the dev server which is now fixed in 3024cbd7088d340ae5b023669617f5ab4c343a7c.
