### ISSUE TITLE
Support configuration of colors in config file

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#193]
Colors are hard-coded by now but should be configurable per instance - at least basic colors such as border/background.

**Comment by stefandesu** [comment]
Unfortunately, LESS is run during build time, so a dynamic change of colors via config file is not possible. I'm currently trying to implement this with a custom .less file where you can override color variables to change the color scheme, but there are still some issues.

**Comment by stefandesu** [comment]
By creating a file in `src/styles/user-colors.less`, color variables can be overridden. This file was added to `.gitignore`.
