### ISSUE TITLE
MappingEditor: don't ignore if current mapping is deleted

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#197]
Steps to reproduce:

1. create and save a local mapping
2. edit the mapping
3. delete the mapping in mapping browser

Result:
- mapping is deleted
- mapping is kept in the MappingEditor
- mapping cannot be saved in the MappingEditor

Expected behaviour:
- mapping is deleted
- mapping is kept in the MappingEditor
- mapping can be saved again in the MappingEditor (as new mapping, to undo deletion)

**Comment by stefandesu** [comment]
Fixed.
