### ISSUE TITLE
Support Geonames vocabulary

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#199]
This requires converting [GeoNames data](https://www.geonames.org/export/) to JSKOS dynamically (wrapper) or from data dump and import into jskos-server. We already a GeoNames webservice but with a different JSON format. Example:

* http://ws.gbv.de/suggest/geonames/?searchterm=E&featureclass=L&country=DE&count=10
* http://uri.gbv.de/terminology/geonames/2805642?format=json

**Comment by stefandesu** [comment]
Will be solved with #142.
