### ISSUE TITLE
Entity lookup is too slow

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#2]
Lookup should be faster than 0.1 seconds and must be faster than 1 second.

**Comment by stefandesu** [comment]
This might be fixed, depending on which requests are considered. Loading a single concept is very fast  (less than 0.5 seconds, usually less than 0.2 seconds), loading the children for a concept takes a little longer (usually between 0.5 and 1 second, depending on the amount of children). Reloading the concept tree after choosing a concept from search is currently very slow, but that doesn't have anything to do with the backend (although it could be faster if loading children was faster).

Should we close this for now and reevaluate performance at a later point, @nichtich?
