### ISSUE TITLE
Support Nomisma vocabulary

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#200]
This requires converting Nomisma data to JSKOS dynamically (wrapper) or from data dump and import into jskos-server. See

* http://nomisma.org/apis (including OpenRefine Reconciliation Service)
* http://bartoc-skosmos.unibas.ch/nomisma/en/ (Nomisma in Skosmos, see #142)

**Comment by stefandesu** [comment]
Nomisma was now added to [jskos-data](https://github.com/gbv/jskos-data), but currently it's using the CSV output of a SPARQL request as a data source, meaning that not all data is included in the conversion. Eventually, it would be better to have either a SKOSMOS wrapper or to convert the RDF dump.

Also, the OpenRefine service works with our provider as well. The only problem there is that they only support http requests, not https, meaning that we're not able to use it when using Cocoda via https...

**Comment by nichtich** [comment]
We need to set up a simple proxy to support SSL for Reconciliation Service.

Existing Nomisma mappings  can further be imported into mapping database.
