### ISSUE TITLE
MappingBrowser: Add tooltip to source

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#205]
Hovering a sources ("Local", "Wikidata"...) should show a tooltip with additional information about the source.

**Comment by stefandesu** [comment]
I copy-pasted the wrong issue title. Commit 0101850 is for #204 and does not implement this feature.

**Comment by stefandesu** [comment]
> Hovering a sources ("Local", "Wikidata"...) should show a tooltip with additional information about the source.

What kind of additional information will there be? Also, should we implement #64 first?

**Comment by nichtich** [comment]
Yes, this issue is not urgent so better implement #64 first.

**Comment by stefandesu** [comment]
Additional information about a registry can now be provided in the `definition` field and will be shown as a tooltip.
