### ISSUE TITLE
Question about sorting by notation

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#206]
Currently, sorting by notation uses strings to sort, i.e. `100` -> `20` -> `3`. This can be confusing however. The question is: Should we use numerical sorting whenever notations consist of numbers only? If yes, how do we determine whether notations within a concept scheme only use numerical notations?

@nichtich

**Comment by nichtich** [comment]
A custom field such as `COLLATION` may be defined for concept schemes with collation rules. [ICU collation](http://demo.icu-project.org/icu-bin/collation.html) should be enough to start with, see [Collator in JavaScript](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Collator). This can also be used for sorting by prefLabel - e.g. GND should better be sorted by this using German sort order.

**Comment by nichtich** [comment]
See also related issue #212

**Comment by stefandesu** [comment]
Fixed in #677.
