### ISSUE TITLE
Get GND from jskos-server to include narrower concepts

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#211]
The current GND wrapper at <http://coli-conc.gbv.de/services/gnd.php> does not include narrower terms, neither does lobid (#40). We might better convert GND MARC dump with mc2skos and index in jskos-server to also get narrower terms. This would also solve #83. Unfortunately mc2skos needs fixes for proper GND conversion: https://github.com/scriptotek/mc2skos/issues/65, https://github.com/scriptotek/mc2skos/issues/64, https://github.com/scriptotek/mc2skos/issues/62.

**Comment by stefandesu** [comment]
I'm not yet convinced that it is a good idea to import, manage, and update the over 8 million GND concepts in our database, "only" to get access to narrower concepts. I'd rather use lobid to access GND instead.

**Comment by stefandesu** [comment]
Experimental access to GND via lobid is now implemented and supports narrower concepts as well.
