### ISSUE TITLE
ConceptDetail: Add Search Links

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#220]
Allow to configure links to external services from a concept, e.g. the concept in a web interface, tools such as ccmapper, catalogs, etc. In ConceptDetail add a tab with "Search Links" that shows a list of links based on configured URI templates. 

Example: Selected RVK class "BD Judaistik":

* [Wikipedia](https://de.wikipedia.org/w/index.php?title=Special:Search&search=Judaistik)
* [Wikipedia (de)](https://de.wikipedia.org/w/index.php?title=Special:Search&search=Judaistik)
* [RVK online](https://rvk.uni-regensburg.de/regensburger-verbundklassifikation-online#notation/BD)
* [ccmapper](https://ccmapper-de-test.pansoft.de/m/mapping.html?id=BD)

search links can be configured via URI template such as

~~~
[
  {
    "prefLabel": { "de": "Wikipedia" },
    "url": "https://{language}.wikipedia.org/w/index.php?title=Special:Search&search={prefLabel}"
  },
  {
    "prefLabel": { "de": "Wikipedia (de)" },
    "url": "https://de.wikipedia.org/w/index.php?title=Special:Search&search={prefLabel}"
  },
  {
    "prefLabel": { "de": "RVK Online" },
    "url": "https://rvk.uni-regensburg.de/regensburger-verbundklassifikation-online#notation/{notation})",
    "schemeUris": ["http://bartoc.org/en/node/533"] 
  },
  {
    "prefLabel": { "de": "ccmapper" },
    "url": "https://ccmapper-de-test.pansoft.de/m/mapping.html?id={notation}",
    "schemeUris": ["http://bartoc.org/en/node/533"]
  },
  {
    "prefLabel": { "en": "WebDewey Search" },
    "url": "https://deweysearchde.pansoft.de/webdeweysearch/executeSearch.html?query={notation}",
    "schemeUris": ["http://bartoc.org/en/node/241"]
  }
]
~~~

Each link can be limited to selected concept schemes. Link URls can be constructed from notation, prefLabel and current language.

**Comment by stefandesu** [comment]
RVK Online currently doesn't work for range notations: #254
