### ISSUE TITLE
Merge config keys helpUrl and feedbackUrl

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#223]
into a `menu` field with arbitrary menu entries (each with url and prefLabel)

**Comment by stefandesu** [comment]
One issue with this: Feedback is not only a link, but opens a modal with an iframe that shows the feedback form. There could be an option to enable a link to be opened in a modal, but that feels kind of hacky and I'm not sure if it will ever be needed for anything else.

Alternatively, we could just open the feedback form in a new tab.

What do you think, @nichtich?

**Comment by nichtich** [comment]
Get rid of the modal and use a simple external link: https://goo.gl/forms/X3eNn2L6OARaKZGr2
