### ISSUE TITLE
SchemeDetail: show languages and dates

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#225]
DANTE also provides `created`, `modified`, and `languages`, e.g: http://api.dante.gbv.de/voc/gender

**Comment by stefandesu** [comment]
I was wondering about the future of SchemeDetail. On the one hand, we'll redesign the scheme selection (#155) which could include more information about a scheme. On the other hand, ConceptDetail already shows some of the fields we want to have for the schemes as well (`created`, `modified`, notes), so it might make sense to merge SchemeDetail and ConceptDetail back into ItemDetail. Neither SchemeDetail nor ItemDetail have much logic of their own, so merging them all together wouldn't be problematic. What do you think?

**Comment by nichtich** [comment]
If the differences are small, both sure can be merged!

**Comment by stefandesu** [comment]
I decided not to merge SchemeDetail and ConceptDetail yet, but I still think it might make sense to do that. Right now, ConceptDetail has some code that needs refactoring which makes the merge more complicated, so I would do that later.
