### ISSUE TITLE
Mapping Notes

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#229]
**Feature request:** Add a note to a mapping when mapping is saved.

Notes and comments on individual mappings are more complex (see #190) but limited notes (where author of note equals author of mapping) can be provided as following:

* Always show JSKOS field `note` in the mapping editor if a mapping has this field
* Provide simple text input field to add a note

Open question: how to show mapping notes in the MappingBrowser.

**Comment by stefandesu** [comment]
I would either show them [using an info icon](https://github.com/gbv/cocoda/issues/201) or by using a separate comment icon that is only shown when a comment exists.

Task List:
- [x] Support mapping notes
