### ISSUE TITLE
Mappings should have a date

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#233]
JSKOS download is missing date of mappings (JSKOS fields `created`/`modified`). I think the reason is that current mappings don't have date at all. At least local mappings should get a timestamp when saved (first `created`, then `modified` if `created` field already exists). This time can also be shown as part of mapping details (additional metadata about a mapping, see #201).

**Comment by stefandesu** [comment]
`created` (when field doesn't exist) or `modified` (when field `created` already exists) will now be adjusted by the BaseProvider before saving mappings.
