### ISSUE TITLE
Move favoriteConcepts to locally bookmarked concepts

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#242]
Remove config key `favoriteConcepts` and introduce concept bookmarking instead where bookmarked concept are locally stored in the browser. This requires #139 to show the list of bookmarked concepts.

**Comment by stefandesu** [comment]
There might still be bugs left, but the first implementation is now pushed to dev. Right now, the only way to add concepts to favorites is by dropping them on the star in the navbar.

**Comment by nichtich** [comment]
This technically solved the issue but is not sufficient from usability point of view. Keep this open until we found a more visible method to star concepts.

**Comment by nichtich** [comment]
`favoriteConcepts` is still included in the config file. I removed it from documentation, it should also be removed from config files and source code (if taken from config file).

**Comment by stefandesu** [comment]
> `favoriteConcepts` is still included in the config file. I removed it from documentation, it should also be removed from config files and source code (if taken from config file).

The `favoriteConcepts` from the config file is used as the default, but it makes sense to remove it.
