### ISSUE TITLE
MappingDetails: Add several missing tooltips

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#247]
* [ ] MappingDetails: tooltip "show all ancestors" also at the ancestors-expand button (angle-down)
* [ ]  MappingDetails: tooltip: "compact ancestors" at the ancestors-expand button (angle-right)
* [ ] MappingDetails: tooltip: "add to mapping" at the plus button

**Comment by stefandesu** [comment]
Do you mean ConceptDetail? Also, the plus button already has a tooltip. ;)
