### ISSUE TITLE
MappingBrowser: show mappings when no concepts are selected

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#252]
This would merge back features of [mapping app](http://coli-conc.gbv.de/cocoda/app/) into Cocoda. If concept schemes are selected, this would show a list of all mappings between the selected concept schemes. Some providers don't support listing *all* mappings or all mappings between selected concept schemes, so include providers which can do so. Main use cases:

* Browse local mappings
* Browse mappings in concordance registry

**Comment by stefandesu** [comment]
Depends on #231.

**Comment by stefandesu** [comment]
Will be a core part of the MappingBrowser rewrite (#231).
