### ISSUE TITLE
Document cocoda-locale-editor

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#258]
The [documentation](https://gbv.github.io/cocoda/) should include a link to cocoda-locale-editor for direct editing locale file ([this link](https://gbv.github.io/cocoda-locale-editor/?fromUrl=https%3A%2F%2Fraw.githubusercontent.com%2Fgbv%2Fcocoda%2Fdev%2Fconfig%2Flocale.json)). If we want to encourage contributing, the link should even be prominent, e.g. in the Settings / Interface Language modal with a sentence that the interface can be translated and translations be corrected. TheSettings dialog should link to the translation tool or its manual from the footer next to the link to GitHub issues.

**Comment by stefandesu** [comment]
I agree. I would also try to add a way to submit the translated file either directly as a pull request on GitHub, or as an email submission.

**Comment by stefandesu** [comment]
Please check the new [section in the docs](https://gbv.github.io/cocoda/#translation) after the Travis build has finished. Thanks!
