### ISSUE TITLE
Add data policy link

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#260]
The data policy link should directly be visible on every page so it must be placed in the menu (setting `menu`) or in an additional footer. The `footer` could replace the config key `impressum` and the footer shown in TheSettings and it could be of same structure like `menu`.

**Comment by nichtich** [comment]
The link could be placed before or after the "help" entry. Feedback is not used anyway so we can remove it, no?

**Comment by stefandesu** [comment]
Currently, the imprint and privacy policy URLs are coming from the authentication server. Should those values be used here as well or should values provided in the config be used here instead?

**Comment by stefandesu** [comment]
> Currently, the imprint and privacy policy URLs are coming from the authentication server. Should those values be used here as well or should values provided in the config be used here instead?

Thinking about this, the authentication server links are completely separate from what Cocoda is doing, so there need to be separate links as well. In our case, they might be the same links, but it's two different systems, so in the config they should be separate.

**Comment by stefandesu** [comment]
I added the links to the navbar. They are still hardcoded in config, so they are separate from `config.menu` at the moment, but we could also move them into `config.menu` if you like.
