### ISSUE TITLE
Refactor config file

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#262]
* [x] favoriteConcepts #242
* [x] language/languages #261
* [x] favoriteTerminologyProviders should be renamed (favoriteVocabularies/Schemes/...?)
* [x] registryMode could be a boolean `includeDefaultRegistries`
* [ ] registryGroups (and registries) needs rethinking. What's the purpose of groups? Isn't it a fixed property of a registry? How and where should groups be configured?

**Comment by stefandesu** [comment]
Regarding `registryGroups`: These are currently used to sort registries into groups at the top of MappingBrowser (i.e. "existing mappings" and "automatic mappings"). If we say that these will be the only groups, we could remove `registryGroups` from the config and instead hardcode it somewhere else. But if someone with their own Cocoda instance would like to use different groups, it would not be possible anymore.

I personally would leave it as it is.

**Comment by nichtich** [comment]
Ok, we can reopen the issue later once we have more overview about registries and possible registry types.
