### ISSUE TITLE
MappingDetails: add action buttons/icons

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#263]
The mapping details should include buttons for the same actions like provided in the MappingBrowser to directly proceed working with an inspected mapping:

* add/edit/view rating (the list of existing ratings can be included)
* edit
* save
* delete

**Comment by nichtich** [comment]
Display of rating should be enough (no editing)

**Comment by stefandesu** [comment]
Rating is now displayed in MappingDetail.
