### ISSUE TITLE
MappingEditor: change comment modal

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#265]
* Newlines in comments should not be supported.
* Instead only take modified comment when the modal is closed with OK or simple enter (right now it is taken into the editor on every keystroke)
* Add a cancel button
* Open the modal when comment is clicked (right now it is only opened with click on the icon)

**Comment by stefandesu** [comment]
> * Newlines in comments should not be supported.

Any particular reason why?

> * Instead only take modified comment when the modal is closed with OK or simple enter (right now it is taken into the editor on every keystroke)
> * Add a cancel button

We had that in the beginning, but it was kind of confusing. If there is a cancel button, there should be an okay/save button as well, and then we have multiple ways of leaving the modal:
- enter (to save)
- save button (to save)
- cancel button (to discard)
- esc button (to save?)

But I guess it would be fine if esc saves the comment as well.

> * Open the modal when comment is clicked (right now it is only opened with click on the icon)

👍

**Comment by nichtich** [comment]
Think about later when review and commenting will be implemented in a broader way.

**Comment by nichtich** [comment]
comment has been removed
