### ISSUE TITLE
MappingBrowser: Unify Registry selection

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#267]
The dropdown at registry groups looks different than the horizontal list of RegistryNotations although it contains the same information. Better not show a dropdown but allow to expand the horizontal list of notations into a vertical list and collapse vice versa. This way users can choose to always show long registry names. Bonus: if there is only one registry in the group, the list is always expanded because it takes the same vertical space anyway.

**Comment by nichtich** [comment]
Next bonus: in the vertical list of registries, each name (or an info icon) could open a modal with RegistryInfo like shown in the settings.

**Comment by stefandesu** [comment]
The dropdown was completely removed with the MappingBrowser rewrite anyway.
