### ISSUE TITLE
Hide ConceptTree if no tree available

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#268]
Just don't show the Concept Tree card if no tree is available anyway.

**Comment by stefandesu** [comment]
Might be confusing in my opinion. People might think that it's a bug because it's not there. If you want, we can at least reduce the height a little bit further, but I think it takes up almost no space and makes things clear.

**Comment by nichtich** [comment]
I'm sure I will come up with this in half a year again... :-)
