### ISSUE TITLE
Introduce config file

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#27]
Custom preferences such as backend URLs `//api.dante.gbv.de/` vs `http://dev-api.dante.gbv.de/` should be put into a config file which can be overridden by local configuration settings not to be put into git repository.

**Comment by stefandesu** [comment]
We could either use something like [node-config](https://github.com/lorenwest/node-config) or implement a simple config system ourselves.

**Comment by nichtich** [comment]
A simple JSON file injested into the application or load on runtime should be enough to start with.

**Comment by stefandesu** [comment]
Added in fbbde53e3ca5cd3da4da2dc54918b68081f5f030 (forgot to reference this issue).
