### ISSUE TITLE
Better indicate occurrences

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#271]
Occurrences of a given concept should better be shown distinct from co-occurrences by adding a straight line or em-dash in the column of the second concept scheme so its more clear that only one concept scheme is references.

**Comment by nichtich** [comment]
To illustrate: In the last row it's unclear why there is nothing in the "to" column:

![cocoda-occ](https://user-images.githubusercontent.com/299856/54359572-3c5dd600-4663-11e9-8588-b0f7b80615f6.png)

maybe add a mid-long line sich as "---" in the concept scheme column and the to column

**Comment by stefandesu** [comment]
This is specific for occurrences, right? Because mappings usually have to have a `toScheme` value (even if there is no concept in there). So I could check specifically if `toScheme` is empty and show the line in those cases.

**Comment by stefandesu** [comment]
Currently, if `toScheme` is empty (like in occurrences), it will be set to the target scheme if one is selected. That way, the "mapping" can still be saved directly. But maybe this isn't necessary, I can't really think of cases where this would be useful. I'd suggest to remove that feature and just show a line to indicate an empty target.

**Comment by nichtich** [comment]
In the example given above the value of `toScheme` seems empty, although it might be set to the current target scheme internally. At least the `To` row should be indicated as explicitly empty by a line.
