### ISSUE TITLE
TheSettings: show message if no local mapping exist

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#276]
The "local mappings" tab should include a message such as

> Local mappings are only stored in your current browser. They are not visible to other users but they may get lost if you purge your browser's local storage. 

The message should be shown at least if no local mapping exist but maybe always.

**Comment by stefandesu** [comment]
Because there is not really any text on that page even when there are local mappings, I thought it would be better to always show that message. Text is still open to debate (especially the German translation...).
