### ISSUE TITLE
Use consistent font sizes

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#28]
ConceptDetail uses 1.2em and 0.8em. ConceptTree uses 1em. ConceptSearch uses 0.875rem; Two sizes (normal and small) or better even one should be enough.

**Comment by stefandesu** [comment]
I agree that we should use consistent font sizes, but can't see how one size should be enough. ConceptDetail is already pretty cramped (even though some information is still missing), and increasing the font size won't help. So either everything will be small, or we need at least a small and a normal font size. I'd suggest maybe 0.8em or 0.85em for small and 1em for normal.

**Comment by nichtich** [comment]
The actual size (0.8em or 0.85em) does not matter it's more to have not more than two sizes. This is also related to #35.

**Comment by stefandesu** [comment]
Now, only two font sizes are used for text: 0.8rem (class `font-size-small`) and 1.0rem (class `font-size-normal`). There is also a class `font-size-large` (1.2rem) which should only be used in the navbar or in component placeholders, if at all.

This will be added to the layout style guide as well.
