### ISSUE TITLE
TheNavbar: Show identity provider icon next to user name when logged in

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#280]
For instance GitHub icon when current identity provider is GitHub. Hovering the icon could show the provider name and link to the identity URI.

**Comment by stefandesu** [comment]
I think if we want to do this, we need to remove something else up there. Currently we have the gear icon, then the name, and then the (colored) person icon that indicates the login status, and all of that is linked to the settings screen. 

I would suggest:
- Remove gear
- Move person icon to the left of the name
- Add the identity provider icon to the right of the name

What do you think?

**Comment by stefandesu** [comment]
I implemented it that way and I think it turned out pretty well. Only problem there is that some icons (especially ORCID) don't fit color-wise onto the background, but we can't really do anything about that.

**Comment by nichtich** [comment]
I'd put the logo in front of the name instead of the current user icon and use the current green user icon as logo fallback. If a logo is shown, the user must be logged in, no?.

**Comment by stefandesu** [comment]
Also a good idea, I'll see how it looks.
