### ISSUE TITLE
Cocoda Login Usabillity Improvement

### ISSUE THREAD

**Issue by DennisTobola** [gbv/cocoda#282]
If you login to Cocoda how about re-arranging the fields

- From: Name, Identity, Login
- To: Name, Login, Identity

Additionally i would add a hint after Identity: "The URI is assigned automatically after the Login"

**Comment by stefandesu** [comment]
I didn't see this before doing some other related changes earlier. How about the current order of fields? I personally would prefer the identity field after the name and then the login stuff. 

> Additionally i would add a hint after Identity: "The URI is assigned automatically after the Login"

This is a good idea, I will add that hint when the user is not currently logged in.

**Comment by stefandesu** [comment]
We should wait until I implement the login/logout buttons before we discuss this further.

**Comment by stefandesu** [comment]
Login buttons are now implemented and I added your hint (see [dev](https://coli-conc.gbv.de/cocoda/dev/)). I'm pretty happy with how it turned out now. What do you say?
