### ISSUE TITLE
Mapping provider "authentification" unclear

### ISSUE THREAD

**Issue by DennisTobola** [gbv/cocoda#286]
Mapping provider -> Concordance Registry, "authentification" with a red lock before is unclear.
Substitute with "You need to be logged-in to save to Concordance Registry"

**Comment by DennisTobola** [comment]
Same with the message if you try to save in the user-interface and get an error message.
A solution would be to remove the save-symbol if you aren't logged-in to avoid confusion.

**Comment by stefandesu** [comment]
> Mapping provider -> Concordance Registry, "authentification" with a red lock before is unclear.
> Substitute with "You need to be logged-in to save to Concordance Registry"

I wanted to keep that part as short as possible. How about "authentication necessary" if not logged in, and "authentication successful" or just "authenticated" when logged in?


> Same with the message if you try to save in the user-interface and get an error message.
> A solution would be to remove the save-symbol if you aren't logged-in to avoid confusion.

Error messages in general need to be improved... But I agree that saving shouldn't even be possible if the user is not logged in. BUT it gets even more complicated: There are providers with authentication that allow you to save mappings without being logged in, but for all other things you need to be logged in.

**Comment by stefandesu** [comment]
I took care of the first point, but the second point is still unclear. For it to work, we would need to query the `/status` endpoint of jskos-server and retrieve the information what can be done with which kind of authentication. I will create a separate issue and move it to the next milestone.
