### ISSUE TITLE
Should you be allowed to review/evaluate your own mappings?

### ISSUE THREAD

**Issue by DennisTobola** [gbv/cocoda#287]
If you create a mapping, you can thumbs yourself up/down.

**Comment by nichtich** [comment]
This may be configurable in the mapping provider: allow upvote (yes/no/allbutyourown), allow downvote (...)

**Comment by stefandesu** [comment]
This has to be configured in Cocoda and in jskos-server. I was wondering if some of this should be available as a separate endpoint in jskos-server so that Cocoda just receives the information from there.

**Comment by nichtich** [comment]
jskos-server has `/status` endpoint (e.g. <https://coli-conc.gbv.de/api/status>) where configuration info could be included.

**Comment by stefandesu** [comment]
Requires https://github.com/gbv/jskos-server/issues/48.

**Comment by nichtich** [comment]
This is no technical but a social question. Let's allow annotation of you own mappings like any other mappings and close this issue.
