### ISSUE TITLE
MappingBrowser: Include voting in table

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#288]
To create a voting annotation it needs two clicks. This could be reduces by putting upvote/downvote button next to the sum in the table cell. Visibulity might depend on available space.

**Comment by stefandesu** [comment]
Does it need two clicks? For me it needs one (hover, then click). I personally wouldn't add more stuff there because there are so many buttons already.

**Comment by nichtich** [comment]
This can be discussed when refactoring of mapping browser and solving #252.

**Comment by stefandesu** [comment]
We have the new MappingBrowser now. I'm still strongly against implementing this because the voting/annotations would take three times as much space as before (button, number, button instead of just number with hover).
