### ISSUE TITLE
RVK Search doesn't find Classes although they exist

### ISSUE THREAD

**Issue by DennisTobola** [gbv/cocoda#296]
When I'm searching "Neuronale Netze" in RVK I get no results.
However, when I'm just searching "Neuronale" i get 3 results which all contain "Neuronale Netze":
- QH 700 Kybernetik. Neuronale Netze 
- ZQ 6280 Neuronale Netze in der Automatisierung
- ST 301 Soft computing, Neuronale Netze, Fuzzy-Systeme

**Comment by stefandesu** [comment]
This is a bug in DANTE. Here are example queries:

- No results for "Neuronale Netze": https://api.dante.gbv.de/suggest?search=Neuronale+Netze&voc=http:%2F%2Furi.gbv.de%2Fterminology%2Frvk%2F&limit=100&count=100&use=notation,label&language=de
- 3 results for "Neuronale" which all include the phrase "Neuronale Netze": https://api.dante.gbv.de/suggest?search=Neuronale&voc=http:%2F%2Furi.gbv.de%2Fterminology%2Frvk%2F&limit=100&count=100&use=notation,label&language=de

**Comment by StiftungAusNachlass** [comment]
Thanks, this is not the expected behaviour, right. It is maybe an elasticsearch-issue, i have to do further analyses

**Comment by stefandesu** [comment]
I'm closing this issue as the RVK is currently served by [jskos-server](https://github.com/gbv/jskos-server) and correctly returns results:

https://coli-conc.gbv.de/rvk/api/suggest?search=Neuronale+Netze&voc=http:%2F%2Furi.gbv.de%2Fterminology%2Frvk%2F&limit=100&count=100&use=notation,label&language=de

**Comment by StiftungAusNachlass** [comment]
It was an error in elasticsearch-wildcard-analyzer. Probably fixed by programmfabrik with next easydb-release 5.50.0 (planned publication on 02.05.2019)

**Comment by StiftungAusNachlass** [comment]
I installed the latest release and now results are returned:
https://api.dante.gbv.de/suggest?search=Neuronale+Netze&voc=http:%2F%2Furi.gbv.de%2Fterminology%2Frvk%2F&limit=100&count=100&use=notation,label&language=de

Is this the expected result, or would you expect only results which contain the whole searchstring at once?

**Comment by stefandesu** [comment]
I'm not sure (@nichtich ?), but at least the order seems off. Those that contain the whole search string should be at the top, shouldn't they? But I guess you don't have any control over that.

**Comment by StiftungAusNachlass** [comment]
The results are sorted alphabetically at the moment.. :-)

**Comment by stefandesu** [comment]
@StiftungAusNachlass Any particular reason why? I would have expected them to be sorted by relevance.

**Comment by StiftungAusNachlass** [comment]
We have some use cases, where we just take the results and put them in dropdowns. I think that's the only reason, which we could bypass by a sort-parameter for /suggest. I am gonna examine, if a order by relevance is responded by easydb-api at all.

**Comment by StiftungAusNachlass** [comment]
Ok, with the order via _score, the result for "neuronale netze"-suggest would be:
```[
    "neuronale netze",
    [
        "Soft computing, Neuronale Netze, Fuzzy-Systeme",
        "Kybernetik. Neuronale Netze",
        "Neuronale Netze in der Automatisierung",
        "H\u00f6henmessung, Nivellement, Trigonometrische Netze, Festpunktbestimmung",
        "Elektroenergiesysteme und -netze",
        "Netze f\u00fcr besondere Zwecke",
        "Netztheorie, Petri-Netze",
        "Betriebsverhalten, Regelung von Elektroenergiesystemen und -netzen",
        "Technisch-\u00f6konomische Probleme der Energieerzeugung, -\u00fcbertragung und Verteilung und Standortfragen bei Energiesystemen und -netzen",
        "Kommunikationsdienste und -netze; Neue Medien; Elektronische Medien",
        "Graphen und Netze allgemein",
        "Graphen und Netze"
    ],
    [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    ],
    [
        "http:\/\/rvk.uni-regensburg.de\/nt\/ST%20301",
        "http:\/\/rvk.uni-regensburg.de\/nt\/QH%20700",
        "http:\/\/rvk.uni-regensburg.de\/nt\/ZQ%206280",
        "http:\/\/rvk.uni-regensburg.de\/nt\/ZI%209280",
        "http:\/\/rvk.uni-regensburg.de\/nt\/ZN%208500%20-%20ZN%208660",
        "http:\/\/rvk.uni-regensburg.de\/nt\/ZN%208565",
        "http:\/\/rvk.uni-regensburg.de\/nt\/ST%20132",
        "http:\/\/rvk.uni-regensburg.de\/nt\/ZN%208520",
        "http:\/\/rvk.uni-regensburg.de\/nt\/ZP%202900",
        "http:\/\/rvk.uni-regensburg.de\/nt\/ZN%206220%20-%20ZN%206240",
        "http:\/\/rvk.uni-regensburg.de\/nt\/QH%20450",
        "http:\/\/rvk.uni-regensburg.de\/nt\/QH%20450%20-%20QH%20452"
    ]
]```

I am gonna ask Jakob how to form the sort-parameter.
