### ISSUE TITLE
More tolerant linking to Cocoda via URL with mapping

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#299]
Linking into the application with a mapping requires the parameters:

* fromScheme
* toScheme
* from
* to
* mapping

The last parameter should be enough ([example link](https://coli-conc.gbv.de/cocoda/app/?mapping=%7B%22from%22%3A%7B%22memberSet%22%3A%5B%7B%22uri%22%3A%22http%3A%2F%2Frvk.uni-regensburg.de%2Fnt%2FZY_6200-ZY_6209%22,%22notation%22%3A%5B%22ZY%206200-ZY%206209%22%5D%7D%5D%7D,%22to%22%3A%7B%22memberSet%22%3A%5B%7B%22uri%22%3A%22http%3A%2F%2Fdewey.info%2Fclass%2F797.23%2Fe23%2F%22,%22notation%22%3A%5B%22797.23%22%5D%7D%5D%7D,%22fromScheme%22%3A%7B%22uri%22%3A%22http%3A%2F%2Furi.gbv.de%2Fterminology%2Frvk%2F%22,%22notation%22%3A%5B%22rvk%22%5D%7D,%22toScheme%22%3A%7B%22uri%22%3A%22http%3A%2F%2Fdewey.info%2Fscheme%2Fedition%2Fe23%2F%22,%22notation%22%3A%5B%22DDC%22%5D%7D,%22type%22%3A%5B%22http%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23broadMatch%22%5D,%22identifier%22%3A%5B%22urn%3Ajskos%3Amapping%3Acontent%3A9b6f96dfded53137d889d72e19d278aeae5e17b9%22,%22urn%3Ajskos%3Amapping%3Amembers%3A7695dba94a314d14a1568f849de30b5fefc40dd6%22%5D%7D)). If no concept scheme and/or no concept is selected left or right, the missing query values of `fromScheme`, `toScheme`, `from`, `to` can be guessed from the mapping.

**Comment by stefandesu** [comment]
I implemented it this way:
- For each side (`from`/`to`):
  - If no scheme was set, set scheme from mapping.
  - If scheme from mapping was set, also set concept from mapping.

In case a scheme was already set in `fromScheme` or `toScheme`, the concept will currently not be set from the mapping. We can add this later by comparing the scheme in `fromScheme`/`toScheme` from the mapping scheme and setting it only when they match.
