### ISSUE TITLE
Add a "next concept" button to ConceptDetail

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#302]
Similar to the button available in ccmapper, there could be a "next concept" button that opens the next available (unmapped?) concept. Further discussion is needed on how this would actually work.

**Comment by nichtich** [comment]
The "next" button action could be configurable:

* don't show next/prev button
* traverse by depth first tree walking (but take care of multi-hierarchies)
* traverse siblings only (to walk through one level)
* traverse unmapped concepts
* traverse mapped concepts
* ...

**Comment by nichtich** [comment]
First implementation should be this:

1. Take the first `broader` of the currently selected concept. 
2. Take the list of its `narrower`
3. Locate the currently selected concept in this list
4. On success show a 'next' button

If clicked, the next concept in the list (2) will be selected. If the currently selected concept is last in the list, select the broader (1) instead.

**Comment by stefandesu** [comment]
I added a first suggestion for this. Your implementation didn't quite make sense to me. Please test my implementation and give feedback whether it makes sense.

**Comment by stefandesu** [comment]
Close after keyboard shortcuts (alt + n, alt + m) were implemented.

**Comment by stefandesu** [comment]
Please test under Linux ~~and Windows~~.

Edit: Works under Windows.

**Comment by stefandesu** [comment]
Works under Linux as well. 👍
