### ISSUE TITLE
TheSettings: Adjust Keyboard-Shortcuts names

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#304]
* shift, alt, and ctrl should be Shift, Alt, Ctrl
* command should be ⌘
* we could also try "⇧" or "⇧ Shift" for shift key

**Comment by stefandesu** [comment]
Unfortunately, the characters ⌘ and ⇧ look weird and too small inside the `<kbd>` tag (see below), so I used `Shift`, `Alt`, `Ctrl`, and `Cmd`.

<img width="288" alt="Screen Shot 2019-04-11 at 09 14 27" src="https://user-images.githubusercontent.com/3275148/55938743-51b32980-5c3c-11e9-81a1-97d86de18efe.png">
<img width="303" alt="Screen Shot 2019-04-11 at 09 12 10" src="https://user-images.githubusercontent.com/3275148/55938744-51b32980-5c3c-11e9-9396-2c0583b98b65.png">
