### ISSUE TITLE
TheSettings: Group data sources / registries

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#305]
See related #257. The data sources are also named "registries", see <https://coli-conc.gbv.de/registry/> for a full list. This list can be grouped by several aspects:

* what a registry contains (mappings, schemes, concepts...). For instance Mapping Providers are providers that contain mappings.
* whether data can be written to the registry (see Mapping providers listed at the Account-Tab)
* ~Configured `registryGroups` (we should just name it "groups" in the interface and internally rename it to `providerGroups` (?))~

**Comment by stefandesu** [comment]
Also allow filtering of registries by their content type (previously in #241).

**Comment by nichtich** [comment]
When extending the "Data Sources" list please also replace the URI link e.g. (http://coli-conc.gbv.de/registry/coli-conc-mappings-dev) with a clickable [link icon](https://fontawesome.com/icons/link?style=solid) so we have less visual noise.

**Comment by nichtich** [comment]
The current separation into databases (aka mapping registries) and data sources is enough for now, we don't need special filter capabilities so far. Open another issue when requested.
