### ISSUE TITLE
rename registry field url to access

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#309]
The [registry field](https://gbv.github.io/jskos/jskos.html#registries) `url` should be used to point to a human readable homepage about a registry but it is currently used as access URL of the API. We should rename the current `url` field to `baseURL` and introduce an `url` field for homepage. Requires also to introduce field `baseURL` in the JSKOS specification. Naming can still be discussed.

**Comment by nichtich** [comment]
* `url` is only use for reconciliation API, so better rename to `reconcile`
* `baseURL` can be removed by explicitly listing each API endpoint URL

**Comment by stefandesu** [comment]
To be finished in #320.
