### ISSUE TITLE
Clean up dependencies

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#315]
Cocoda has too many dependencies, causing the app bundle to be pretty big. Analyze which dependencies take up most of that space and find a way to remove them.

**Comment by stefandesu** [comment]
Using [source-map-explorer](https://www.npmjs.com/package/source-map-explorer), I analyzed our Webpack vendors file. Here's a screenshot of that analysis: 

<img width="2672" alt="Screen Shot 2019-03-27 at 09 24 22" src="https://user-images.githubusercontent.com/3275148/55060709-54295700-5072-11e9-9c83-3567d74c9932.png">

You can see where we can easily improve our bundle size:
- [x] Only import those font-awesome icons that we actually use.
- [x] Only import lodash functions that we actually use.
- [ ] Figure out a way to reduce bootstrap-vue imports, or use only the CSS but not the JavaScript from bootstrap-vue *([see this](https://bootstrap-vue.js.org/docs/#individual-components-and-directives))*.
- [x] Do we actually need validation for JSKOS objects in Cocoda? `ajv` surprisingly takes almost 100 KB. Alternatively we could move JSKOS validation to an API. *See comments below for more discussion.*
- [ ] Why is [vue-flexible-table](https://github.com/stefandesu/vue-flexible-table) so big? It has zero dependencies and shouldn't take up 21 KB. Same issue with some other modules. *(Something to do with ES6 modules?)*

Just by addressing the first two points, we can reduce the bundle size by over 1 MB.

**Comment by stefandesu** [comment]
Just the font-awesome thing reduced the bundle size from around 2 MB to around 1 MB. I think it would be good to reduce the size further to a maximum of 500 KB, but that's not a priority.

**Comment by nichtich** [comment]
JSKOS validation is only required in the `dev` branch, isn't it?

**Comment by stefandesu** [comment]
So far, I wasn't able to find a way to conditionally import a module when using Vue.js. I'm sure there's some solution using Webpack, but there doesn't seem to be a simple way to do it. Also, I just noticed that validation is included in `jskos-tools`, meaning that we either have to split off validation into its own package again, or just live with it.

I'm still surprised that it takes up around 100 KB, it feel like it should be a lot less than that...

Edit: The minified browser version of `ajv` is also 120 KB in size, so we can't do anything about that. We could use [djv](https://github.com/korzio/djv) instead which seems to be only around 30 KB in size, but I'm not sure what the differences are.

**Comment by stefandesu** [comment]
Update: Using [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash), I was able to reduce the size of lodash without any effort. It only saved 30 KB or so, but better than nothing. Here's a current image for the dependency sizes:

<img width="2560" alt="Screen Shot 2019-04-03 at 08 08 36" src="https://user-images.githubusercontent.com/3275148/55456805-4fbbeb80-55e8-11e9-9323-d256c893ccb0.png">

**Comment by stefandesu** [comment]
Moved this to 2.0.0 because the changes resulting in the biggest effect are already implemented.
