### ISSUE TITLE
Connection breakups with Cocoda/(login problems?)

### ISSUE THREAD

**Issue by DennisTobola** [gbv/cocoda#316]
After logging in, Cocoda freezes from time-to-time. After the freeze ends a message pops up, saying "Du bist jetzt eingeloggt". This message normally only appears after the first login.
Cause: unknown

**Comment by stefandesu** [comment]
I can imagine that there are too many HTTP requests lined up, causing Cocoda to freeze/be sluggish and causing the connection with login-server to break. I can imagine that #317 and #83 might help with this.

**Comment by stefandesu** [comment]
@DennisTobola If this still happens, feel free to reopen the issue, but it should've gotten much better with the recent improvements.
