### ISSUE TITLE
MappingBrowser: Load information about concepts in fewer requests

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#317]
Currently, MappingBrowser loads labels (and notations if necessary) for all concepts in all mappings each with a separate request. These requests should be bundled by concept registry, i.e. having only a single request for all concepts from jskos-server and another single request for all concepts from DANTE. This would greatly improve performance when there are a lot of mappings or suggestions shown.

- [x] Add option to load multiple concepts to `providers/concept-api-provider.js`.
- [x] Add option to load multiple concepts to `mixins/objects.js`.
- [x] Use that new option in MappingBrowser.

**Comment by nichtich** [comment]
Bundling by concept scheme may be enough to and cleaner to implement.
-- 
Jakob Voß via Android

**Comment by stefandesu** [comment]
@nichtich Any particular reason why bundling by concept scheme may be cleaner to implement? It would actually introduce one more unnecessary step because we still need to retrieve the provider from the concept scheme to make the request. As provider information is also associated with concept objects, we'd save one step and possibly a few requests by using that directly.
