### ISSUE TITLE
Improve resizing of top level components

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#32]
Possible improvements on #24:

- [x] Prevent unwanted text selection while resizing.
- [x] Allow minimizing of components.
- [x] Improve minimum size calculation (e.g. the mapping component can become very narrow).
- [x] Try to make the whole logic less verbose (right now it has to be implemented on the parent component as well as each individual component that needs to be resizable). See also [this suggestion](https://github.com/gbv/cocoda/issues/34#issuecomment-395353598).
- [x] Fix issues when minimizing resized components (in certain cases the remaining component(s) won't fill the rest of the space).

**Comment by nichtich** [comment]
Minimizing components would support different usage scenarios such as:

![component-sizes](https://user-images.githubusercontent.com/299856/40770192-4212396e-64ba-11e8-817c-01550b39150a.png)

We could also provide these set of "dashboard layouts" (or how to call them) from the navbar to switch between.

**Comment by stefandesu** [comment]
Minimizing and resizing is basically perfected now. 👍
