### ISSUE TITLE
Clean up specification of registries

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#320]
The existing registries use a couple of fields, only some of which are [specified as part of JSKOS](https://gbv.github.io/jskos/jskos.html#registries):

~~~
$ curl 'https://coli-conc.gbv.de/registry/registries.ndjson' | jq -r keys[] | sort | uniq -c | sort -nr
     14 uri
     14 provider
     14 prefLabel
     14 notation
     12 definition
      9 subject
      4 mappings
      3 url
      3 scheme
      3 namespace
      3 baseUrl
      2 suggest
      2 schemes
      2 data
      2 concepts
      2 canSaveMappings
      2 canRemoveMappings
      2 autoRefresh
      1 types
      1 searchUris
      1 occurrences
      1 excludedSchemes
      1 concordances
      1 auth
      1 annotations
~~~

Not all details need to be specified in JSKOS but the current mix of possible fields seems too much to be manageable. Maybe move some options into the `provider` field (implementation)?

Related issue: https://github.com/gbv/cocoda/issues/309

**Comment by stefandesu** [comment]
- [x] Remove `url` (rename to `reconcile`, see #309)
- [x] Merge `scheme` into `schemes` (needs small adjustments in provider implementation)
- [x] Remove `namespace`, instead use `namespace` from scheme that was loaded through an API (registries need to be adjusted after schemes are loaded)
- [x] remove `baseURL`
- [x] remove `canSaveMappings`, `canRemoveMappings`, and `auth` (are now loaded from API, see #293)
- [x] remove `searchUris`, instead provider will receive a list of all registries and take the search URIs from there
