### ISSUE TITLE
Use TypeScript?

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#324]
We could start using [TypeScript](https://www.typescriptlang.org) in Cocoda to reduce the possibility of errors regarding types. It is possible to use [TypeScript in Vue](https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-typescript), so we could start by using it in one component at first, for example for the rewrite of MappingBrowser (#231).

**Comment by nichtich** [comment]
TypeScript is very popular but adds another level of complexity and knowledge required to contribute. If we introduce it in selected parts, we should first think about #74.

**Comment by stefandesu** [comment]
Yeah, that's true. We can keep it in mind for the future, but for now I'll close this issue again.
