### ISSUE TITLE
IMPORTANT! Creatorfield is empty, can't delete mappings

### ISSUE THREAD

**Issue by DennisTobola** [gbv/cocoda#333]
See title
https://coli-conc.gbv.de/cocoda/dev/?fromScheme=http%3A%2F%2Furi.gbv.de%2Fterminology%2Fbk%2F&toScheme=http%3A%2F%2Furi.gbv.de%2Fterminology%2Frvk%2F&from=http%3A%2F%2Fld.zdb-services.de%2Fresource%2Forganisations%2FZDB-1-CUBB&to=http%3A%2F%2Frvk.uni-regensburg.de%2Fnt%2FLH%252021670

Second time try
https://coli-conc.gbv.de/cocoda/dev/?fromScheme=http%3A%2F%2Furi.gbv.de%2Fterminology%2Fbk%2F&toScheme=http%3A%2F%2Furi.gbv.de%2Fterminology%2Frvk%2F&from=http%3A%2F%2Furi.gbv.de%2Fterminology%2Fbk%2F1-2&to=http%3A%2F%2Frvk.uni-regensburg.de%2Fnt%2FMN%2520-%2520MS

Saving coli-conc recommendations mappings lets me delete them. -- So it seems to only affect the ones created by yourself.
Update: saving the mappings in "Local" lets me delete them, too. So there seems to be a problem with the Concordance Registry?

**Comment by stefandesu** [comment]
I'm very confused. Could you describe exactly what you did and what the problem is? Where did those mappings come from?

**Comment by DennisTobola** [comment]
* I create mappings
* the creatorname is missing 
* I can't delete the created mappings, the little red trashbin is missing right now
* when I create mappings on "local" i can delete the mappings

Or is it a feature, that you are unable to delete your mappings, if you save in Concordance Registry and only certain people are able to?

I just noticed: there aren't creatornames ANYWHERE, i assume I can't delete my mappings, because only the creator can delete them 
![Screenshot_2019-04-24 Cocoda](https://user-images.githubusercontent.com/37077998/56640840-41f00800-6674-11e9-8bc0-bc5d93f8aaab.png)

**Comment by stefandesu** [comment]
Ah, the problem is that the creator of the mapping does not get written for some reason. This is not about deletion, but only about the creator. In Concordance Registry, you are only able to delete mappings that you have created yourself, so if the creator is somehow omitted from the mapping, it cannot be checked whether it's your own mapping. I'll look into this.

**Comment by stefandesu** [comment]
Issue is fixed and new release was created.
