### ISSUE TITLE
Add selection of mapping registry via drop-down in the navbar

### ISSUE THREAD

**Issue by DennisTobola** [gbv/cocoda#342]
In addition to #307 we should add a drop-down menu, when clicking the icon, to select the registry without needing to go into the settings every time.

![Screenshot_2019-05-06 Cocoda(1)](https://user-images.githubusercontent.com/37077998/57213265-91282800-6fe6-11e9-9657-37bcdccde2f8.png)

**Comment by stefandesu** [comment]
Yes, I had this in mind back then as well.
