### ISSUE TITLE
Better integrate data for a single entity from different sources

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#347]
For example: If a concept is first loaded through a mapping which also includes the `prefLabel`, but only the English one, and then the same concept is loaded through from the concept API with way more information, the new information for a specific property is not integrated.

I'd like to do this for either version 0.9.0 or at the very latest for 1.0 because it seems pretty important to me.

**Comment by nichtich** [comment]
This depends on the kind of information. For non-existing languages and fields it makes sense to merge data but existing fields may conflict among sources
-- 
Jakob Voß via Android

**Comment by stefandesu** [comment]
> This depends on the kind of information. For non-existing languages and fields it makes sense to merge data but existing fields may conflict among sources

Yes of course. I've been thinking that it would make sense to merge objects deeply, so not just add properties on the top level, but going down as well. That would basically fix the problem. There might even be an existing Lodash method for this, depending on how much control we want to have.

**Comment by stefandesu** [comment]
There's also another problem related to this: If there are parts of an object that come from a source like local storage (e.g. when a concept is saved to favorites) that are loaded first, but actually are outdated, those parts will not be updated. This could also happen if for example prefLabels are saved in the mapping itself, but usually mappings should only contain the URI and maybe notation for concepts.

The question is whether some parts should be overridden with information coming from another source, for example when detailed information about a concept is requested.

**Comment by stefandesu** [comment]
> There's also another problem related to this: If there are parts of an object that come from a source like local storage (e.g. when a concept is saved to favorites) that are loaded first, but actually are outdated, those parts will not be updated. This could also happen if for example prefLabels are saved in the mapping itself, but usually mappings should only contain the URI and maybe notation for concepts.

The issue specific to favorite concepts has been fixed with 6327208, but I think a general improvement is necessary nonetheless.

**Comment by stefandesu** [comment]
In the context of another project, we will soon have the issue that concepts' `prefLabel`s are updated by adding them to the concept in a mapping, but at the moment, that change would not be integrated into the existing concept (if already loaded) because only new data (e.g. a `prefLabel` in a new language) will be integrated. Therefore, I think we need a more sophisticated way of integrating data from different source. Either we'll say that data that is loaded later overrides existing data (but only primitive values, e.g. if `prefLabel.de` and `prefLabel.en` are already there and a new `prefLabel.de` comes from some API, only that one will be replaced), or that we use modified dates and use the "newer" data (e.g. we would need to add a modified date to concepts in the mappings for the aforementioned case).

What do you think, @nichtich?

**Comment by nichtich** [comment]
May be relevant later but no real bug without real life example.
