### ISSUE TITLE
Split developer documentation and user manual

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#349]
The user manual and developer documentation should not be in one place, but rather separate. The former should be linked from the application, while the latter only needs to be linked from the README. Also, certain information from the developer manual should be available in the README as well (already started).

**Comment by nichtich** [comment]
See #337 (partly duplicate). We're working on it in the `docs/` directory. A build should create files `user-manual-de.html` and `user-manual-en.html`, copied into `dist/`.

**Comment by nichtich** [comment]
See #337 (partly duplicate). We're working on it in the `docs/` directory. A build should create files `user-manual-de.html` and `user-manual-en.html`, copied into `dist/`.

**Comment by nichtich** [comment]
The German user-manual is an independent document, while the english is collected from the full manual. To close this issue we should move the English user manual but this is less urgent.

**Comment by nichtich** [comment]
The API reference, build with vue-styleguide should also be split up into a independent document because build time is slow and inflexible compared to Pandoc.

**Comment by nichtich** [comment]
The user-manual references boostrap.css from dist directory so it won't look nicely if no build has been run (e.g. if someone tries to only work on the manual), this should also be fixed.

**Comment by nichtich** [comment]
This also includes documenting new features such as concept lists which have not been covered in documentation yet.
