### ISSUE TITLE
Extend web layout style guide

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#35]
To ensure a consistent layout we should create a [style guide document](http://styleguides.io/) that lists all conceptual elements and actions of the application. These would later likely be mapped to CSS classes but elements and their style should better be discussed independently from technical implementation. The style guide would contain elements such as

* notation of a concept
* preferred label of a concept
* notation/label of a concept when hovered for selection
* notation when hovered to show concept details
* external link (link that does not trigger some action in the application but leads to another URL)
* dropdown menu
* mapping/concept when hovered for deletion
* ...

In a later step we could try out and discuss different styles of these elements with a web designer

**Comment by nichtich** [comment]
See also the [design guideline for Folio](http://ux.folio.org/docs/design-guidelines/principles/), another project developed at GBV.

**Comment by stefandesu** [comment]
A first version of the guidelines now exist (d7c7dac3cbf81d7087102dae89d95bece63dd7ee, https://gbv.github.io/cocoda/#design-guidelines). Because it is not at all a full version of the guidelines, we should leave this issue open for now.
