### ISSUE TITLE
Specify minimum node version in package.json

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#350]
As [described here](https://stackoverflow.com/questions/29349684/how-can-i-specify-the-required-node-js-version-in-package-json).

**Comment by stefandesu** [comment]
I would suggest requiring Node.js 10 as it is the current LTS version and supported until 2021. Node.js 8 (previous LTS) is in maintenance and won't be supported after 2019. 

https://nodejs.org/en/about/releases/

Edit: Cocoda works fine with Node.js 8 (8.16.0 in this case), but it comes with an older version of npm (6.4.1) which will produce a different package-lock.json than is committed in the repository. So allowing Node.js 8 would cause conflicts regarding to that.

**Comment by stefandesu** [comment]
Note that the `engines` property in package.json 1. can't enforce using a specific Node version, and 2. doesn't even show a warning on `npm i`. It only shows the warning if the package is used as a dependency which is not the case for Cocoda.

We can still add it to the file to indicate the recommended Node version. I will also add it to the README and documentation.
