### ISSUE TITLE
Support undo of mapping deletion and a "trash bin" for deleted mappings

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#354]
- [x] When a mapping is deleted, there is a message "Mapping was deleted." That message should 1. stay a bit longer than other messages, and 2. include an undo button to restore that mapping in case it was deleted accidentally.

- [x] Additionally, recently deleted mappings could be kept in a "trash bin" from which they can be restored later if necessary. This trash bin should be either restricted by time (only keep the recent 7 days, for example), and/or by number of deleted mappings (only keep the last 10 deleted mappings).

**Comment by DennisTobola** [comment]
I would try to put the trash bin in between 'feedback' and the star for favorites. 
Any settings can then be adjusted in 'Settings' -> 'Trashbin' (new subitem).
These are just suggestions, whether you implement them or not is up to you.

**Comment by stefandesu** [comment]
Not sure about adding a new tab to settings just for this, but we can try to put it in the navbar. 

I also forgot to mention that I would add a Ctrl/Cmd + z shortcut to undo the last deletion, but depending on how you look at this it can get complicated quickly. Like, should it also undo creating or editing a mapping? Should it still undo deletion if it happened half an hour ago? And so on. Any thoughts on this?

**Comment by nichtich** [comment]
Not everything needs to be undoable. Registries can support version history but that would be another issue.
-- 
Jakob Voß via Android

**Comment by stefandesu** [comment]
Requires #356.

**Comment by stefandesu** [comment]
Note: This would not be a traditional "undo" of deletion of a mapping, but rather a "restore" in the sense that it will be saved again. This means that it will get the latest modified date as well as a new URI (in case of jskos-server at least). I don't think that this is a problem, but it's a caveat to keep in mind.

**Comment by stefandesu** [comment]
jskos-server now allows a pre-given URI when POSTing a mapping, so that at least the URI can remain the same. Local mappings already have support for this.

**Comment by stefandesu** [comment]
Please try out the first implementation of this idea in dev.

Some notes:
- ~~No "undo" mapping on the "Mapping deleted" alert yet.~~ -> it's there now
- ~~Trash can needs to be clicked to be opened (inconsistent with favorite concepts?).~~ -> made consistent with favorite concepts
- ~~Trash uses old MappingTable component where the table header is not localized.~~ -> localized and adjusted MappingTable
- ~~It's not yet clear from which registries the mappings are (but the information is saved, so you can delete and restore mappings from different registries).~~ -> added registries
- ~~Only the last 5 mappings are kept.~~ -> increased to 10
- ~~Deleted mappings are not saved in locale storage (yet?), which means they are lost when the page is reloaded.~~ -> now saved to local storage
