### ISSUE TITLE
Local: cocoda.json empty registries

### ISSUE THREAD

**Issue by DennisTobola** [gbv/cocoda#355]
If no registry is set in config/cocoda.json, there is an empty space, where the mapping editor should be. Everything to do with said problem doesn't exist on the local instance.

**Comment by stefandesu** [comment]
I know that having no registries configured looks very weird at the moment, but then again, what does Cocoda do if you have no registry?

> Everything to do with said problem doesn't exist on the local instance.

I don't understand that sentence, can you elaborate?

**Comment by nichtich** [comment]
If you start with no registries configured, there should be a message telling you to configure registries, I think that's all. Same applies if registries are configured to get schemes but no registries to retrieve mappings so the mapping editor cannot be used.

**Comment by stefandesu** [comment]
That's a good idea.

**Comment by stefandesu** [comment]
There's now a message with a link to documentation when no registries are configured at all, and if there are registries for schemes/concepts, but none for mappings, the whole middle part will be hidden. I guess the last part could be solved better, especially because there are still mapping related elements in the rest of the application. What do you think?

**Comment by nichtich** [comment]
I've unified the message with malformed or missing config file, we could further differentiate possible configuration errors. 

> I guess the last part could be solved better, especially because there are still mapping related elements in the rest of the application. What do you think?

This requires some more refactoring to make sure all mapping-related information is only shown if there is a mapping provider. This will likely come up again with #74 and #371: In the future it should be possible to configure Cocoda to only show a vocabulary browser or only only concordances (ConcordanceApp as configured instance of Cocoda). For this particular issue nothing more is needed.
