### ISSUE TITLE
Add feature to transfer local mappings to a different registry

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#357]
Assuming a user has created a bunch of mappings locally in their browser, and they now decided to save them into our Concordance Registry. Currently, there is no easy way of doing this. There should be an option, maybe under Settings -> Local Mappings, to transfer your local mappings to a different registry. Some caveats/questions:

- There should be a preview of all the mappings that will be imported into the other registry.
- Should the local mappings be deleted? (I would add a checkbox for this in the preview window.)
- If the local mappings are not deleted, how can we ensure that mappings are not transferred twice? (Idea: After transfer, update the local mappings to include the registry's URIs, so next time they will get updated, but not saved as a new mapping.)
- Should there be an additional command line tool to batch save mappings into jskos-server without having access to the server? (This would need to use authentication via login-server etc.)

**Comment by nichtich** [comment]
> Should the local mappings be deleted?

I guess thist must selectable ("move" vs. "copy")

> If the local mappings are not deleted, how can we ensure that mappings are not transferred twice?

The basic idea behind copying is to have things twice afterward, no? This must be solved at the target where mappings are copied to: the registry decides when to see two mappings as same and whether a duplicate is generated or not.

> Should there be an additional command line tool to batch save mappings into jskos-server

Maybe in the long run. jskos-server first requires some general cleanup and documentation. In doubt: no.

**Comment by stefandesu** [comment]
> The basic idea behind copying is to have things twice afterward, no? This must be solved at the target where mappings are copied to: the registry decides when to see two mappings as same and whether a duplicate is generated or not.

This would mean that currently in jskos-server, a duplicate would be created every time as there are no checks for duplicate mappings. If that's fine, then this can be implemented that way. In theory I completely agree with you, but in practice people will want to copy their local mappings to the server and in case they want to keep their local mappings, this would result in lots of duplicates if they do this transfer regularly.

If we took this one step further, we could make it a "sync" option: All the user's mappings can be synchronized between the local storage and a mapping registry, meaning that all local mappings will be copied to the server (and afterwards replaced by the mapping that was saved on the server to preserve URI etc.) and all the user's mappings from the server will be copied to local storage. I honestly don't think this would be very hard to implement, we would only need a method in jskos-server to return all mappings for the currently authorized user.

**Comment by stefandesu** [comment]
For now, add a "one click move button" in MappingBrowser to move a mapping from local into concordance registry.

**Comment by stefandesu** [comment]
Please reopen if there are further suggestions or if it doesn't work correctly.
