### ISSUE TITLE
MappingBrowser: add link to data modal

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#362]
The link to open a data modal can be placed on or after the number of mappings, e.g. 

* *4 mappings* => data modal shows JSKOS data of this 4 mappings and an API link
* *5 of 384.594 mappings* => data modal shows JSKOS data of this 5 mappings and an API link

**Comment by stefandesu** [comment]
Yes I was wondering how to implement this, but your suggestion seems like a sensible solution. 👍
