### ISSUE TITLE
MappingEditor: Select direction and type of mapping

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#37]
Mappings can also have a type (first URI in field `type`). These types should be selected together with the mapping direction. Good symbols need to be found for each combination:

symbols | URI
------ | ---------------
⥢ ⥤ ⇐ ⇒ ⟸ ⟹| <http://www.w3.org/2004/02/skos/core#exactMatch>
← → ⟵ ⟶ | <http://www.w3.org/2004/02/skos/core#closeMatch>
\> ⥸ | <http://www.w3.org/2004/02/skos/core#broadMatch>
\< ⥶ | <http://www.w3.org/2004/02/skos/core#narrowMatch>
↜ ↝ ⇜ ⇝ ⬿ ⤳ | <http://www.w3.org/2004/02/skos/core#relatedMatch>
⤎ ⤏ ↼ ⇀ | <http://www.w3.org/2004/02/skos/core#mappingRelation>

broadMatch/closeMatch probably don't make sense in both directions, they are more likely to be from broader to narrower concept

**Comment by stefandesu** [comment]
How about something like this?

 ![this](https://media.giphy.com/media/1UUOrhi3PcRFbj3FAw/giphy.gif)

(This is made with Vue.js transitions.)

**Comment by stefandesu** [comment]
Suggestion: Instead of allowing the mapping to be reversed (which would introduce yet another element in the interface and make it more crowded and confusing), should we maybe allow the user to switch sides, i.e. swap the left and right schemes and therefore the mapping? This would make it clear that a mapping is always from left to right. The button for this action could be in the middle of the navigation bar, for example.

**Comment by nichtich** [comment]
Yes, swapping sides seems less confusing. Let's keep this independent issue for a later version. We'll still have the five mapping types above (plus another I forgot for "unknown mapping type" `http://www.w3.org/2004/02/skos/core#mappingRelation`).

**Comment by stefandesu** [comment]
I already noticed that when I went through the JSKOS specification earlier. Should this be added as well? If yes, should it be selectable? What symbol should it have (maybe a question mark)?

Otherwise I'm almost finished implementing this.

**Comment by stefandesu** [comment]
Another questions: Has the mapping type anything to do with what kind of relation the mapping is, i.e. whether to use memberSet (one-to-many relation) or memberChoice (many one-to-one relations)? If not, we need a way to choose whether the mapping is one-to-one or one-to-many (related to this issue, but could be a separate issue as well).

**Comment by nichtich** [comment]
Selection of memberSet (AND) vs. memberChoice (OR) vs. memberList (AND with order) is #45.

**Comment by stefandesu** [comment]
Could you also answer my previous question about the "unknown mapping type":

> Should this be added as well? If yes, should it be selectable? What symbol should it have (maybe a question mark)?

Except for that, this issue is done.

**Comment by nichtich** [comment]
Symbols are far too large and the mappingTypeHeader/mappingTypeDescription can be removed. Maybe [Material Design guidelines for radio buttons](https://material.io/design/components/selection-controls.html#radio-buttons) can help for inspiration.

**Comment by stefandesu** [comment]
> Symbols are far too large and the mappingTypeHeader/mappingTypeDescription can be removed. Maybe Material Design guidelines for radio buttons can help for inspiration.

I just pushed another update, could you take a look? I was unsure how the guidelines for radio buttons could help though.

**Comment by nichtich** [comment]
Solved so far with <https://github.com/gbv/cocoda/pull/48>. User feedback is needed to clarify icon symbols and to check whether dropdown may be a better interface.

**Comment by stefandesu** [comment]
I'm closing this issue for now (we can always reopen later if necessary).
