### ISSUE TITLE
Add an indicator for selected mappings in mapping search and mapping navigator

### ISSUE THREAD

**Issue by DennisTobola** [gbv/cocoda#373]
You'll be able to find your current mapping faster, also if there are duplicate mappings, you won't know which you selected.
An example would be the same background coloring as selected concepts.

![Screenshot_2019-05-27 Cocoda Mapping Tool (dev)](https://user-images.githubusercontent.com/37077998/58419562-40f33180-808b-11e9-9450-6df91061db74.png)
___

Or make it the same color used for the mapping browser in general to have continuity with our color palette and also organize the different sections with their own colors.

![Screenshot_2019-05-27 Cocoda Mapping Tool (dev)(1)](https://user-images.githubusercontent.com/37077998/58419764-bfe86a00-808b-11e9-9ab4-5b3de92b3852.png)

I would rather take the latter, but that's just my opinion.

**Comment by stefandesu** [comment]
This is actually there in theory, but for some reason it doesn't seem to work anymore. Will fix tomorrow.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by stefandesu** [comment]
I liked your idea of using the same highlight color as in ConceptTree, so that's how I implemented it now.
