### ISSUE TITLE
Create intro/onboarding

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#38]
For example with one of these frameworks:

- https://github.com/usablica/intro.js
- ~~http://bootstraptour.com~~ -> https://github.com/IGreatlyDislikeJavascript/bootstrap-tourist (fork of bootstrap-tour with lots of fixes)
- ~~https://github.com/shipshapecode/shepherd~~

**Comment by nichtich** [comment]
Given the complexity of mapping we should also create short videos and upload them at YouTube for outreach and additional documentation.

**Comment by nichtich** [comment]
maybe something like this with annotated screenshots is also a good start: http://blog.lobid.org/2018/07/04/lobid-gnd-suche.html

**Comment by nichtich** [comment]
This would be nice but not worth the complexity: nothing beats a live hands-on workshop, otherwise #511 and the existing documentation should be enough, ok?

**Comment by stefandesu** [comment]
What you are describing in #511 is basically what I was thinking of when I created this issue. I'm not sure how you were thinking of implementing that other than using a library like the ones I mentioned above.

**Comment by nichtich** [comment]
Ok, closing this in favour of #511
