### ISSUE TITLE
Use FontAwesome icons to improve interface

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#39]
For example:

[![](https://i.imgur.com/vuhJ9kQ.png)](https://imgur.com/a/yo3rcuA)

**Comment by nichtich** [comment]
This is related to #35. A very simply Markdown document with this screenshot and a list of icons to style could be a start.

**Comment by stefandesu** [comment]
Added with 9cff7151ba2625db853db6cf9fc34e14cea7c9a6. Will be added to the layout style guide as well.
