### ISSUE TITLE
Mapping Search: Add option to show one's own mappings

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#392]
Currently, this is possible by putting the name in the creator filter, but it should be easier and use the creator URIs instead of the name.

Changes in jskos-server and local mappings might be necessary for this.

**Comment by nichtich** [comment]
Searching by author via typeahead may be an option but probably harder to implement.

**Comment by stefandesu** [comment]
This is now implemented as a button that inserts one's own URIs into the creator field. I think typeahead is a great idea, but definitely harder to implement because we need to query each server for  possible creators and assemble the results somehow. I'll create a separate issue for that.
