### ISSUE TITLE
Support long concept lists with pagination

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#4]
Large numbers of broader concepts should be rare but may exist, but large numbers of top concepts are common especially in flat systems. Pagination and/or scrolling is needed to support such long lists of concepts.

This issue is probably not relevant for DDC, BK, and RVK so low priority.

**Comment by stefandesu** [comment]
An example for this would be the "Museen Stade: Strassennamen" in DANTE:
http://api.dante.gbv.de/voc/museenstade_strassennamen/top?properties=notation
http://api.dante.gbv.de/voc/museenstade_strassennamen/top?properties=notation&offset=100
and so on. (Good for testing.)

**Comment by stefandesu** [comment]
Solved by adding a higher limit parameter to the API requests.

**Comment by nichtich** [comment]
How does this affect performance? Unfortunately the total maximum number is not known in advance so we need to support pagination at some point, but with low priority.

**Comment by stefandesu** [comment]
Okay, fair enough!

**Comment by nichtich** [comment]
The `X-Total-Count` header should give the total number of a truncated list but this is not implemented properly at DANTE API.

**Comment by nichtich** [comment]
Possible example is Wikidata's instance-of relationship translated to narrower in JSKOS.

**Comment by stefandesu** [comment]
Related to #139.

**Comment by stefandesu** [comment]
This will probably be necessary at some point, but we're closing it for now until we have a specific use case where it's necessary.
