### ISSUE TITLE
In cocoda the various areas are not updated or cleared when a new search is submitted

### ISSUE THREAD

**Issue by annakasprzik** [gbv/cocoda#402]
See screenshot -- 
![Update](https://user-images.githubusercontent.com/25246212/58948683-f3fa1400-878a-11e9-8972-adb78487c8cb.PNG)

Various areas show elements of three different searches -- "Papaya", "Pädagogik", and "Koala".

**Comment by stefandesu** [comment]
As far as I understand, this is not a bug, but rather a combination of a misunderstanding about how Cocoda works and a slightly confusing user interface.

First of all, the Mapping Editor is completely separate from the other components and its content will not change automatically.

The "problem" here is I think the search field. In your case, you must have selected "Antipädagogik" on the left first, and then "Papayas, Avocados, Mangostanen" on the right. Selecting it on the right automatically filled both search fields with "Papayas" (cut off from the full label) (this should be improved, see #397), but not change selected concepts. The results shown in the Mapping Navigator are the mappings related to the selected concepts on both sides.

Any suggestions on how to improve the UI to make it clearer?

**Comment by annakasprzik** [comment]
Hm, maybe underly the areas that automatically interact with each other with a different colour than those where you have to explicitly drag concepts to in order to make them cross the barrier to that component?

**Comment by stefandesu** [comment]
This is too general, but we're happy to talk about more specific suggestions.
