### ISSUE TITLE
Better document mapping types

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#404]
Especially >, <, and -> need better names, and a short description both in the UI and in the manual.

**Comment by stefandesu** [comment]
The mapping types are coming from Wikidata, so should the names be adjusted there, or should we better split off from Wikidata again?

See https://github.com/gbv/jskos-tools/issues/9 and your [commit](https://github.com/gbv/jskos-tools/commit/b5a9774adadd3e7d8b5526ecb112a93ee14d5147).

**Comment by nichtich** [comment]
I updated the labels and added `definition` (to show together with the labels on mouseover) in jskos-tools 0.2.7. The definition should also be shown in Mapping-Details modal

**Comment by nichtich** [comment]
The tooltip in mapping search show English names also if user interface language is set to German. The `definition` could be appended with `: ` to the label.

**Comment by stefandesu** [comment]
Do the definitions need to be added in Mapping Search as well? My suggestion would be to only add them in Mapping Editor.

**Comment by nichtich** [comment]
> Do the definitions need to be added in Mapping Search as well? My suggestion would be to only add them in Mapping Editor.
It's enough to show them in mapping editor.
