### ISSUE TITLE
ConceptDetail: Add star button to add concept to favorites

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#407]

**Comment by nichtich** [comment]
Related issue #408

**Comment by DennisTobola** [comment]
The star button should be next to the marked concept, right? 

![Screenshot_2019-06-06 Cocoda Mapping Tool (dev)(1)](https://user-images.githubusercontent.com/37077998/59022768-b959af80-884e-11e9-9c21-95629ee67827.png)
