### ISSUE TITLE
Favorite button improvements

### ISSUE THREAD

**Issue by DennisTobola** [gbv/cocoda#408]
- [ ] clickable instead of hovering
- [ ] bigger 'Hitbox'

**Comment by stefandesu** [comment]
I'm not sure about the "clickable" aspect. I'm all for reducing the number of clicks necessary to access a feature. How about, in addition to the bigger hitbox, we add a delay in hiding the window?

**Comment by stefandesu** [comment]
I added two improvements to the favorite button:
- Debounce hiding the dropdown (forgot to add the issue number to the commit). This means that it's not hidden immediately, but only after half a second.
- Increase drop target. So you don't have to drag a concept onto the star anymore, but around the star is fine as well.

Please test this if this is sufficient. Simply increasing the hitbox is not possible without increasing the space as well (and its hitbox is pretty large already). I'm not a fan of using clicks to open it, although if there's a strong argument for it, we could implement it. Please reopen this issue if necessary.
