### ISSUE TITLE
Remove API method topByNotation

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#42]
It is possible to query top concepts via concept scheme URI this way: 
<http://api.dante.gbv.de/voc/top?uri=http://uri.gbv.de/terminology/bk>

**Comment by stefandesu** [comment]
Will be done as soon as a bug in DANTE has been fixed (http://api.dante.gbv.de/voc returns scheme URIs with a trailing / while http://api.dante.gbv.de/voc/top?uri= expects the URI to not have a trailing /).
