### ISSUE TITLE
Move setting tabs to menu dropdown

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#422]
Clicking or hovering the user name should show a menu with setting items (Accounts, Layout,...). See GitHub for inspiration.

![image](https://user-images.githubusercontent.com/299856/59503515-e1758e00-8ea0-11e9-94c8-05749c717786.png)

**Comment by stefandesu** [comment]
I added this with 3a26678dc22866df6efa2d44b3611f4a057a2bc7.
