### ISSUE TITLE
Support concept lists

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#425]
Continuation of #139.

Currently, there are two lists:
- Top Concepts
- Favorite Concepts

There are certainly more ideas for lists:
- list of concepts not mapped yet
- more than one custom list
- lists with custom queries

Question/points to discuss:
- Should there be more lists?
- If yes, how should they be shown? (Currently not enough space for more lists)
- If yes, we might finally need to add pagination (#4) if the resulting list is too long.

**Comment by nichtich** [comment]
How about two tabs "Concept Tree" and "Concept Lists" where the latter can show different lists. I am unsure how to *select* which list to show. Maybe like the scheme selection? One possibility might be to select list in the settings. An yes, we need pagination.

One additional idea for a list to start with: In the typeahead search field a number is shown "42 results". This result set could be converted into a list.

> more than one custom list

We could have a "save favorites as list" feature, so there is only one favorites list but it can also be used for collecting concepts.

**Comment by stefandesu** [comment]
> How about two tabs "Concept Tree" and "Concept Lists" where the latter can show different lists. I am unsure how to _select_ which list to show. Maybe like the scheme selection? One possibility might be to select list in the settings. An yes, we need pagination.

I could also imagine a dropdown arrow on the second tab title that allows changing the list.

> One additional idea for a list to start with: In the typeahead search field a number is shown "42 results". This result set could be converted into a list.

Good idea!

> We could have a "save favorites as list" feature, so there is only one favorites list but it can also be used for collecting concepts.

I understand where the idea is coming from, but I feel like there should be a better way to do this. Maybe a popover for the favorite star (after a short delay) that shows other lists and allows creating new custom lists. I think that's kind of what YouTube is doing with their playlist (add to "Watch Later" by default, but allow adding to a custom list with the same button).

**Comment by stefandesu** [comment]
As a first implementation, we could add a config field "lists" which is an array of URIs which offer registry-like objects with infos (prefLabel etc.) and the `concepts` key with the concepts in the list. Those lists can be selected instead of "Favorite Concepts" via a dropdown menu.

**Comment by nichtich** [comment]
The `conceptList` could support both URLs and hard-coded lists as JSKOS Registry objects with field `concepts`, `prefLabel` (mandatory), and `scopeNote` (optional):

~~~json
{
  "conceptLists": [
    "http://example.org/a-list.json",
    {
      "prefLabel": { "en": "important concepts" },
      "scopeNote": { "en": ["please map these concepts first"] } 
    }, 
    "concepts": [ { "uri": "..." }, { "uri": "..." }, ... ]
  ]
}
~~~

**Comment by nichtich** [comment]
See <https://coli-conc.gbv.de/lists/rvk-ohne-bk-top250.json> for a sample lists to be configured with the Cocoda instance at <http://coli-conc.gbv.de/cocoda/rvk/> (with schemes limited to RVK, BK, DDC, GND, Wikidata and local mappings disabled).

**Comment by stefandesu** [comment]
I added a first implementation, but I need to fix how additional lists are shown (currently only as additional tabs which doesn't really fit, so all the titles are cut off) and there are no lists configured on any instance yet (the RVK instance tracks master so we can't test it there either).

**Comment by stefandesu** [comment]
You can test it by using a custom config with the `config` parameter: 

https://coli-conc.gbv.de/cocoda/dev/?config=https%3A%2F%2Fraw.githubusercontent.com%2Fstefandesu%2Fcocoda-configs%2Fmaster%2Fconcept-list.json&fromScheme=http%3A%2F%2Furi.gbv.de%2Fterminology%2Frvk%2F

**Comment by nichtich** [comment]
Thanks, I've enabled lists at <https://coli-conc.gbv.de/cocoda/rvk/?fromScheme=http%3A%2F%2Furi.gbv.de%2Fterminology%2Frvk%2F>. What I found:

* [x] The component needs a data sources icon to show where the list came from
* [ ] put favorites and other lists in a dropdown instead of multiple tabs because we likely get more lists (RVK-BK and RVK-DDC to start with)
* [x] use short name of list (`notation`?) if available
* [x] show scopeNote on hover

**Comment by stefandesu** [comment]
For the data sources, I linked the top concepts and the URL for the list. This is slightly inconsistent because the list includes more than just the concepts, but we can't link only to the concepts, so it should be fine.

I'll have to think about how to properly implement the dropdown, it's not an easy task.

**Comment by stefandesu** [comment]
Please take a look at the latest change. There's only one list now and I added a chevron button with a popover to change the current list. The tooltip with the scope note will now be shown when hovering inside the options in the popover, not on the tab title anymore. I'm open for suggestions on how to improve this before we close this issue.
