### ISSUE TITLE
Support single-vocabulary Terminology Providers via config file

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#43]
For instance like this:

~~~json
[
  { "url": "//api.dante.gbv.de/" },
  {
    "voc": [ {
      "uri": "http://bartoc.org/en/node/430",
      "prefLabel": { "de": "Gemeinsame Normdatei" },
      "notation": ["GND"]
    } ],
    "data": "http://coli-conc.gbv.de/services/gnd.php",
    "suggest": "https://ws.gbv.de/suggest/gnd/?searchterm={searchTerms}"
  }
]
~~~

The `voc` service is hard-coded with a fixed result set. The `data` service is given with base URL, for instance <http://coli-conc.gbv.de/services/gnd.php?uri=http://d-nb.info/gnd/1-2>. The `suggest` service is given with URL template. Other services (`top`, `ancestors`) are not supported.

**Comment by stefandesu** [comment]
This can now be tested on branch `api-overhaul`. I'll leave this issue open as there's still some refactoring and cleaning to be done on this.
