### ISSUE TITLE
Wikidata suggest returning mixed language labels

### ISSUE THREAD

**Issue by DennisTobola** [gbv/cocoda#438]
I set the Layout to english, but I'm still getting german results, despite the Wikidata items having English labels as well.

![Screenshot_2019-07-09 Cocoda Mapping Tool (dev)](https://user-images.githubusercontent.com/37077998/60883294-17145980-a24a-11e9-8fb2-9213e1e5e007.png)

**Comment by stefandesu** [comment]
Fixed in 4f7bc170bf46fc239a9ab16d37e6e9eaf581c6f1.
