### ISSUE TITLE
Add reload button to mapping search

### ISSUE THREAD

**Issue by DennisTobola** [gbv/cocoda#439]
If someone works on mappings and saves them, people searching in the mapping search won't see the new mappings.

**Comment by DennisTobola** [comment]
Nevermind, it updates automatically.

**Comment by stefandesu** [comment]
For future reference: Registries can be configured to auto refresh regularly. Currently, this is configured for local mappings (every 5 seconds) and concordance registry (every 10 seconds). Local mappings are refreshed in case Cocoda is used in multiple tabs at the same time.
