### ISSUE TITLE
Show a message, if cookies are deactivated

### ISSUE THREAD

**Issue by DennisTobola** [gbv/cocoda#440]
Some people deactivate the cookies alltogether, the Problem is, Cocoda won't load in that case. So there should be at least a message for people to know, what to correct, for example, if JavaScript is deactivated.

![Screenshot_2019-07-10 Cocoda](https://user-images.githubusercontent.com/37077998/60946719-33b69d00-a2ef-11e9-9253-1914df81a416.png)

**Comment by stefandesu** [comment]
In theory, Cocoda should work fine even without cookies. The only place where Cocoda needs cookies is for the login, but Cocoda can be used without the login. For some reason though, access to local storage is blocked when cookies are disabled (couldn't find any references for that online), which is what causes Cocoda to not work when cookies are disabled.

We can still include a cookie check and show a message that the login won't be available when cookies are disabled (for a cookie check, see [this](https://stackoverflow.com/a/43923580/11050851)).

**Comment by stefandesu** [comment]
I extended the error message above to include cookies and added a code snipped that shows it when cookies are disabled as well. 

Eventually, this should be removed again though and be superseded by making the app work without local storage (see #441).
