### ISSUE TITLE
Show moderated annotations when available

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#442]
To support "moderated" (aka approved, reviewed, checked...) mappings, annotations of motivation `moderating` (see [Web Annotation Data Model](https://www.w3.org/TR/annotation-model/#motivation-and-purpose)) should be supported in a special way:

* if a mapping has been checked (that is iff an annotation exists with motivation "moderating"), show a check mark instead of the voting icon. In this case voting is not possible via the user interface anymore and voting results are not directly visible
* the "Mapping Details" modal shows all existing annotations (votings and checks)

How to create moderation annotations is not part of this issue. In KENOM this is done with another user interface. We could also allow a way to check mappings for selected users or user groups via Cocoda interface but this would be another issue.

The mapping search should have an option to limit search to checked mappings but this is also another issue.

See also #351 for a third kind of annotation to possibly support.

**Comment by stefandesu** [comment]
Should the annotation with motivation `moderating` have any value in `bodyValue`? I couldn't find suggestions for that anywhere, but from the description it seems that `moderating` should have some value associated with it.

**Comment by nichtich** [comment]
As [described here](https://www.w3.org/TR/annotation-model/#cardinality-of-bodies-and-targets) the `body` (or `bodyValue`) is optional, so an annotation would look like this:

~~~json
{
  "@context": "http://www.w3.org/ns/anno.jsonld",
  "type": "Annotation",
  "id": "https://coli-conc.gbv.de/api/annotations/...",
  "target": "https://coli-conc.gbv.de/api/mappings/...",
  "motivation": "moderating",
  "creator": { ... },
  "created": "..."
}
~~~

**Comment by stefandesu** [comment]
I added support for annotations with motivation "moderating". Currently it shows a checkmark instead of the vote count, and in the popover the moderating annotation is shown as well (also with a checkmark). Voting is still possible however, should that be removed? (Note that it would only be removed from the UI, voting via the API would still be possible.)
