### ISSUE TITLE
MappingBrowser: Extend mapping transfer button

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#447]
The mapping transfer button is currently hardcoded to transfer mappings from local registry to concordance registry. This should be changed to show the transfer button for mappings of *all* concordance registries except for the registry which is currently selected for writing into. The transfer button should allow transfer of mappings from any registry into the currently selected registry.

**Comment by stefandesu** [comment]
What you are describing is basically what the save button in MappingBrowser does, only that it won't delete the old mapping. We could also do it like this:

- For existing mappings (L/C/W), only the transfer button is shown to transfer the mapping into the currently selected registry. In case that the user doesn't have the rights to delete the mapping, it'll show the normal save button.
- For mapping recommendations, the save button will be shown as usual.

What do you think?

Also, we could implement this in version 1.1.0.

**Comment by stefandesu** [comment]
We decided to remove the button altogether until we find a better solution (like a batch transfer from local mappings into a different registry).
