### ISSUE TITLE
Comment field in mappings is kind of slow

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#453]
Not sure what is happening there, but typing in the field is pretty laggy.

**Comment by nichtich** [comment]
Is the comment field used anyway? I'd prefer to remove it as it seems to have been a workaround for annotations.

**Comment by stefandesu** [comment]
I opted to still show the comment even in Mapping Editor (but removed the functionality to edit it). Do you think we should remove that as well and only show it in the Mapping Details (if it exists for older mappings)? 

As for as I can see, we only used it to mark HUB examples.
