### ISSUE TITLE
Normalize Scheme URIs

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#46]
Mappings use BARTOC URIs (e.g. http://bartoc.org/en/node/533 for RVK) while DANTE uses uri.gbv.de (e.g. http://uri.gbv.de/terminology/rvk/ for RVK). This makes it difficult to compare schemes.

**Comment by nichtich** [comment]
To start with, additional URIs can be given in JSKOS field `identifier` and DANTE API provides lookup of this field via query parameter `id`, e.g. <http://api.dante.gbv.de/data?id=https://bartoc.org/en/node/533>. This may be a workaround. In practice, URIs of concept schemes need to be rewritten/normalized at several places.

**Comment by stefandesu** [comment]
Okay, as a workaround I will look for matches between the `uri` and `identifier` fields of both sides when comparing schemes.

**Comment by stefandesu** [comment]
Note that not even the BARTOC URIs are always the same. The field `identifier` returns the URIs with https while they use http in the mappings. I will add a "replace https with http" to the workaround...

Also, the BARTOC URIs in the mappings seem to use http://bartoc.org/en/ while DANTE uses https://bartoc.org/de/.
