### ISSUE TITLE
Support annotation of mappings from another registry

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#460]
By now only concordance registry allows annotation of mappings and annotations are stored into the same concordance registry. At least for Wikidata we need to decouple this if annotation is wanted.

**Comment by stefandesu** [comment]
I think this should be possible to do VERY easily. Let me try it out and I'll report back.

**Comment by stefandesu** [comment]
Okay, I was a bit overenthusiastic, it is not that easy.

For this, we would need to add a way to direct certain functionality from one registry to another one, i.e. say "for annotations, please use this registry". It shouldn't be that hard to implement, but definitely not as easy as I thought.

**Comment by stefandesu** [comment]
Is this something that we will definitely implement (so it can stay for milestone 1.2.0) or is there further discussion needed?

**Comment by nichtich** [comment]
Better move this after more workflow details have been done. In particular #470 is needed first.

**Comment by stefandesu** [comment]
In #667, we've been discussing that annotations will automatically get invalidated once the mapping content (i.e. members or type) changes. This would only be possible if annotations are kept in the same database as the annotated entities. If we were to use annotations for annotating foreign entities (let's say a Wikidata mapping), then we couldn't automatically invalidate that mapping.

If we're still unsure about this issue, I would suggest removing the milestone for now.

**Comment by nichtich** [comment]
This feature might be needed for other use cases but not in our current applications, so closing this.
