### ISSUE TITLE
Jump to first page of results if a mapping is saved or updated

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#463]
If I go to page 5 of the results in Mapping Search and edit a mapping there, it will move to the top when saved, so it looks like the mapping disappeared. When a mapping is saved or updated, the search results of the registry should jump to page 1.

For Mapping Navigator, the same could apply but only if the mapping was previously in the result set (which doesn't have to be the case).

**Comment by stefandesu** [comment]
This requires more thought and feedback from users. I can very well imagine a scenario where jumping to page 1 is not at all intended by the user.

**Comment by stefandesu** [comment]
@DavidBRohrer Do you have an opinion on this? Otherwise I would postpone this to some other time.

**Comment by guitarster** [comment]
My first thought is, that jumping to page 1 after saving is not so good. I can imagine, that a user wants to edit more than one mapping and in this case he/she hase to click to page 5 again and again. 
Best solution would be, to show the edited mapping at the same position as before.

**Comment by stefandesu** [comment]
> Best solution would be, to show the edited mapping at the same position as before.

I guess that would make sense, but it would also break the whole logic of how the mappings are shown. Right now, they are sorted by last modified date, descending, so if a mapping is edited, it will move to the very top (first page, first mapping).

In theory, we could change it to sorting by creation date where the sort order would remain stable. @nichtich what do you think?

**Comment by nichtich** [comment]
In most cases sorting by creation date and sorting by modification date is equal because only some mappings are edited at all. For this reason changing the default sorting to creation date seems best. If we have an option to sort by modification date instead, disappearing of an edited mapping is ok, so no jumping to the first page in both cases.

**Comment by stefandesu** [comment]
I adjusted the default sort order for mapping search to created. I would suggest that we close this issue and make this selectable in #671.
