### ISSUE TITLE
Mapping Browser: Button to show all mappings between currently selected systems

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#465]

**Comment by nichtich** [comment]
Currently selected systems should also be used by default when opening the mapping search. Maybe a switch to always sync selected scheme and search schemes? Icon could be https://fontawesome.com/icons/lock and https://fontawesome.com/icons/lock-open.

**Comment by stefandesu** [comment]
That's a good idea. The switch would need to automatically "unlock" as soon as the user edits the search scheme though because we don't want to override the user's decision.

**Comment by stefandesu** [comment]
I added a first implementation, but to be honest, I'm not fully convinced yet. Maybe it's because in this implementation, I disabled the input field if the field is locked. Maybe you can take a look @nichtich. Also I'd be happy about text suggestions for the German tooltip on the lock/unlock buttons.

**Comment by stefandesu** [comment]
I adjusted it to make it closer to what I had originally intended.

**Comment by nichtich** [comment]
Looks good except for the color: better use blue or grey instead of red/green

**Comment by stefandesu** [comment]
> Looks good except for the color: better use blue or grey instead of red/green

I think the color is important as a clear visual indicator whether it is locked or not. It doesn't have to be red/green though, we could use dark grey/light grey or something like that. Let's talk about it on Monday.
