### ISSUE TITLE
Mapping Search: hide extended search

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#466]
Searching by creator, mapping type, and or concordance is a rather special kind of search, so don't show these fields if they are empty. The search form could be collapsed and made expansible to "extended search" showing all search fields.

**Comment by stefandesu** [comment]
How would you suggest the layout to be if we did this? There is not enough space in the first row to show the registries and the buttons, so we would need a second row anyway.

I could imagine instead of hiding the extended search to move the position of elements depending on the component size.

**Comment by nichtich** [comment]
Like this (with larger chevron icon at the right):

![image](https://user-images.githubusercontent.com/299856/64692130-a4676a80-d494-11e9-9ee0-e82e67a67384.png)

Registries can go to extended search as well.

**Comment by nichtich** [comment]
A filter icon might better fit to open the extended search.

**Comment by stefandesu** [comment]
I added a first implementation of this. I felt that chevrons fit much better than the filter icon (I wouldn't expect it to expand/collapse when clicking on a filter icon). 

Two questions:
- Do we need tooltips on the chevrons?
- If someone has enabled some other filter, e.g. type, and then collapses the extended filters, it will still filter on type. Should we somehow indicate that another filter is active when it is collapsed?

**Comment by nichtich** [comment]
> Do we need tooltips on the chevrons?

Yes: "extended search"

> If someone has enabled some other filter, e.g. type, and then collapses the extended filters

If an extended filter is enabled, the search should not be collapsible. Or use the filter icon with green dot as used at other places. This icon is not obvious if never used before but consistent.

**Comment by stefandesu** [comment]
> If an extended filter is enabled, the search should not be collapsible.

I implemented it this way for now. But I just had another idea, maybe you can say whether you like that better. If the search is collapsed, the filter icon is shown (with green dot if an extended filter is active). If the search is extended, the chevron up icon is shown for collapsing it again. What do you say?

**Comment by stefandesu** [comment]
This is fine for now, but we can improve it later. I'm moving the milestone.

**Comment by stefandesu** [comment]
> But I just had another idea, maybe you can say whether you like that better. If the search is collapsed, the filter icon is shown (with green dot if an extended filter is active). If the search is extended, the chevron up icon is shown for collapsing it again.

I now implemented it this way. Please take a look and provide feedback, thanks!

**Comment by nichtich** [comment]
I only have my mobile phone, giving an incomplete impression. Thoughts: the labels "Type:" and "Konkordanz:" can be omitted
-- 
Jakob Voß via Android

**Comment by stefandesu** [comment]
> I only have my mobile phone, giving an incomplete impression. Thoughts: the labels "Type:" and "Konkordanz:" can be omitted

That's true, but that wouldn't save any vertical space, so we can as well leave the labels. I think it's fine as long as the collapsed search is as concise as possible.

**Comment by nichtich** [comment]
The "Search" button should not change its position when search filters are expanded.

**Comment by stefandesu** [comment]
> The "Search" button should not change its position when search filters are expanded.

Done. 

Closing this issue now. Please reopen if there's anything else.
