### ISSUE TITLE
API URLs missing for reconciliation services

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#472]
Opening the data modal for registries and reconciliation services (mapping suggestions) should include the API URL. Right now the API URL is only included when opening the data modal from mapping search. [Example](https://coli-conc.gbv.de/cocoda/dev/?fromScheme=http%3A%2F%2Fbartoc.org%2Fen%2Fnode%2F1940&toScheme=http%3A%2F%2Furi.gbv.de%2Fterminology%2Fbk%2F&to=http%3A%2F%2Furi.gbv.de%2Fterminology%2Fbk%2F08&from=http%3A%2F%2Fwww.wikidata.org%2Fentity%2FQ15763113)

**Comment by stefandesu** [comment]
Added API URLs for reconciliation specifically and fixed an issue that prevented the URL to show for Mapping Navigator results. Note that it does currently not work for Nomisma reconciliation as it requires POST requests.

**Comment by nichtich** [comment]
Looks like API URL is missing again in Wikidata Reconciliation service ([example](https://coli-conc.gbv.de/cocoda/dev/?fromScheme=http%3A%2F%2Ficonclass.org%2Frdf%2F2011%2F09%2F&toScheme=http%3A%2F%2Fbartoc.org%2Fen%2Fnode%2F1940&mapping=%7B%22from%22%3A%7B%22memberSet%22%3A%5B%7B%22uri%22%3A%22http%3A%2F%2Fwww.wikidata.org%2Fentity%2FQ19786%22,%22notation%22%3A%5B%22Q19786%22%5D%7D%5D%7D,%22to%22%3A%7B%22memberSet%22%3A%5B%7B%22uri%22%3A%22http%3A%2F%2Ficonclass.org%2F71%22,%22notation%22%3A%5B%2271%22%5D%7D%5D%7D,%22fromScheme%22%3A%7B%22uri%22%3A%22http%3A%2F%2Fbartoc.org%2Fen%2Fnode%2F1940%22,%22notation%22%3A%5B%22WD%22%5D%7D,%22toScheme%22%3A%7B%22uri%22%3A%22http%3A%2F%2Ficonclass.org%2Frdf%2F2011%2F09%2F%22,%22notation%22%3A%5B%22iconclass%22%5D%7D,%22creator%22%3A%5B%7B%22uri%22%3A%22https%3A%2F%2Fwww.wikidata.org%2Fwiki%2FUser%3AJakobVoss%22,%22prefLabel%22%3A%7B%22en%22%3A%22JakobVoss%22%7D%7D%5D,%22type%22%3A%5B%22http%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23exactMatch%22%5D,%22created%22%3A%222019-10-25T11%3A10%3A15.215Z%22,%22modified%22%3A%222019-10-25T11%3A10%3A15.215Z%22,%22identifier%22%3A%5B%22urn%3Ajskos%3Amapping%3Acontent%3A531df170ef023ed942b2177bdc8da8f47459d2dd%22,%22urn%3Ajskos%3Amapping%3Amembers%3A034d12ae40c14249d8ee7341777606353e3d4c84%22%5D,%22uri%22%3A%22https%3A%2F%2Fcoli-conc.gbv.de%2Fapi%2Fmappings%2F52dae2a0-b8d5-4427-9b6c-17605aa76066%22%7D&mappingUri=https%3A%2F%2Fcoli-conc.gbv.de%2Fapi%2Fmappings%2F52dae2a0-b8d5-4427-9b6c-17605aa76066&from=http%3A%2F%2Ficonclass.org%2F11G)

**Comment by stefandesu** [comment]
Works for me:

![Screen Recording 2019-11-28 at 11 34 25](https://user-images.githubusercontent.com/3275148/69772447-53cdf680-11d3-11ea-9d7f-98c14aa77dde.gif)
