### ISSUE TITLE
Make selection of writeable registry more obvious

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#473]
Given a non-logged in user, mapping search looks like this:

![image](https://user-images.githubusercontent.com/299856/64337236-3d9f0880-cfdf-11e9-88d0-8480234a48c0.png)

* The buttons "edit" and "save as mapping" at Concordance Registry might be misunderstood as provide editing/saving the mapping in Concordance Registry

The mapping table looks the same if the user is logged in and has right to edit Concordance Registry and Wikidata-Mappings

* It should be made more clear which registries can be selected for editing

**Comment by stefandesu** [comment]
> * The buttons "edit" and "save as mapping" at Concordance Registry might be misunderstood as provide editing/saving the mapping in Concordance Registry

I think the icon for the "save as mapping" button is fine since we changed it to the arrows, but we could adjust the tooltip to include the target registry ("save as mapping in Local"). For the edit button, would it make sense to have different icons depending on whether it's the currently selected registry or not? Not sure what kind of icon would make sense.

> * It should be made more clear which registries can be selected for editing

So some kind of visual indicator? Maybe an icon [like this](https://fontawesome.com/icons/user-edit?style=solid) with a tooltip?

**Comment by nichtich** [comment]
* Adjusting the tooltip ("save as mapping into Local") is a good idea.
* The user-edit icon could be shown on each registry's title bar (after the number of mappings, see also #471) either bold or non-bold with tooltip "use this registry to write mappings into".
* The edit button for non-selected registries could be shown
   * if user has right to write into the registry: show edit button and automatically switch selected registry on click
   * otherwise show a copy-button and create a copy instead of editing the original mapping

**Comment by stefandesu** [comment]
> * The user-edit icon could be shown on each registry's title bar (after the number of mappings, see also #471) either bold or non-bold with tooltip "use this registry to write mappings into".

I would have put it after the name. Or do you think at the end makes more sense because that's where all the other action icons for the mappings are?

**Comment by nichtich** [comment]
Just try out what looks better

**Comment by stefandesu** [comment]
To make it consistent across the application, I put the icon right after the name. It is now used in Mapping Browser, in the dropdown from the navbar, and in Settings under Data Sources.

Further tasks (from above):
- [x] Adjust the tooltips with the name of the registry.
- [x] Adjust the edit button as described [above](https://github.com/gbv/cocoda/issues/473#issuecomment-528322166).

**Comment by stefandesu** [comment]
I implemented it like discussed. Please reopen if there are further suggestions or if something is not working correctly.
