### ISSUE TITLE
Indicate mapped concepts in concept detail

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#479]
In ConceptDetail narrower concepts and ancestors should also be indicated with a green border if there is a mapping. The setting can be the same like in concept tree (toggle on/of for both together)

**Comment by stefandesu** [comment]
I added it for ancestors, broader, narrower, and even the selected concept itself. Please tell me if that's too much though.

Also, the mapped status is currently loaded through the concept tree, meaning that ConceptDetail won't load the mapping status for the concepts shown in there. I will try to add that shortly.

**Comment by stefandesu** [comment]
Please test the extensively and have a look at the console for any errors that might occur. If everything works and there are no errors, we can close the issue.

**Comment by stefandesu** [comment]
Sorry, forgot to commit one file, please wait for the next build!
