### ISSUE TITLE
TheNavbar: Quick selection of interface language via dropdown

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#480]
When mapping multilingual vocabularies such as Wikidata and EuroVoc it helps to quickly change languages. This could be supported by another dropdown in the navbar. The currently selected language should be shown by notation/code (`en`, `de`) to save space.

**Comment by stefandesu** [comment]
Should we add country flags or just the code for now?

Note that this is one of the things that we have discussed multiple times already and went back and forth on. But it makes sense to be able to quickly switch language for those multilingual vocabularies.

**Comment by nichtich** [comment]
A more complex solution would be to differentiate interface language and vocabulary language. The latter could be changed individually in the settings of conceptSchemeSelection, this would be at most three clicks.

**Comment by stefandesu** [comment]
Not sure if this is necessary anymore since you can now define a list of preferred vocabulary languages separate from the interface language. (#619)
