### ISSUE TITLE
SchemeDetail: show which registries are used to query a vocabulary

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#481]
The detail info about a vocabulary should include information about the data source which is used to query this vocabulary. For instance EuroVoc is queried from BARTOC Skosmos. The data source could be shown the same way like in TheSettings: Data sources.

**Comment by stefandesu** [comment]
I added it, but I'm not completely satisfied with how it looks. Any suggestions on how to improve it? I think I'd rather show only one line with "Registry: [notation] Name of registry".

**Comment by nichtich** [comment]
A simple line such as "Sources: {notation} {label}" should be enough.
