### ISSUE TITLE
Support selecting non-writeable registry

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#484]
Mapping registries should be allowed to select as active registry also if the user is not allowed to write into them. One reason is the green indicator of existing mappings is based on registry selection. Selecting a non-writeable registry is only possible by a hack:

* login
* select non-local registry
* logout (the selection is not changed)

**Comment by stefandesu** [comment]
You can now select non-writeable registries. I marked those registries which can't be used to save mappings with a warning icon (both in the selecting in the navbar and in MappingBrowser). The icon might not be necessary in MappingBrowser though, and we can use a different icon/color if you want.

**Comment by nichtich** [comment]
Well, a warning writing should be reserved to when user action is required to fix something. How about the reverse: show  an "edit" icon for writeable registries.

**Comment by stefandesu** [comment]
> Well, a warning writing should be reserved to when user action is required to fix something. How about the reverse: show an "edit" icon for writeable registries.

Yeah, I had a similar thought after reading through #473 again, so I agree.

**Comment by stefandesu** [comment]
I now used the user-edit icon for registries that can be used to save mappings. It is also consistent across the application.
