### ISSUE TITLE
Cleanup locale strings

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#489]
Get all used locale strings (not including dynamically used keys):

~~~
git grep -Eh '\$t' | grep -Eo "[$]tc?[(](\"[^\"]+|'[^']+)" | sed 's/^....//' | sort | uniq > locale-used.tmp
~~~

Get all defined English locale strings

~~~
jq -r '.en|path(..)|[.[]|select(type=="string")]|select(length==2)|join(".")' config/locale.json | sort | uniq > locale-defined.tmp
~~~

Show difference

~~~
diff locale-{defined,used}.tmp | egrep '^[<>]'
~~~

The locale file should also be reorganized to possibly reuse and/or remove labels and unify terminology.

**Comment by stefandesu** [comment]
The regular expressions aren't perfect, but I manually went through them and found a total of 21 unused keys that I removed from the file.
