### ISSUE TITLE
Support config file without need to rebuild aplication

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#49]
The application needs to be rebuild for configuration changes to take effect. If `cocoda.json` is loaded on run-time instead, configuration could be changed locally on the web server. This might also be extended to configuration stored in a database and changing settings with an admin interface in the application.

**Comment by stefandesu** [comment]
Use Webpack to keep the configuration files out of the app bundle.

**Comment by stefandesu** [comment]
`cocoda.json` from the `config/` folder will now be copied to the root folder during build, and loaded when the application is started. This means that `cocoda.json` can be swapped out without rebuilding the application.

Cocoda also offers a URL parameter `config` now. The default value is `./cocoda.json`, but any URL can be given with the parameter. This means that an existing instance of Cocoda (e.g. dev or master) can be used with a different config file if necessary, for examples when used in a live presentation.
