### ISSUE TITLE
MappingBrowser registry header is not fully clickable

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#492]
Only the left half of this header is clickable to select the registry because of some flex settings:

![image](https://user-images.githubusercontent.com/299856/65941013-46da9400-e42a-11e9-85bf-199fa108051b.png)

**Comment by stefandesu** [comment]
It was the way it was to fix the pagination in the middle. I adjusted it so that the pagination is positioned absolutely and the registry name spreads over the whole header.
