### ISSUE TITLE
Implement "locked browsing" mode

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#493]
Implement a mode (enabled via settings) to automatically select mapped concepts on both sides. This means: If a concept is selected then:

* look up mappings in the currently selected registry going from the selected concept to a concept in the other scheme (that's eventually what the green *does-a-mapping-exist* indicator does)
* if it's one mapping to one concepts, select the mapped concepts in the other side
* if there are multiple mappings, order them by mapping type (exact, close, broader/narrower, related) and take the best
* if the best mapping is one-to-mapping don't do anything

**Comment by stefandesu** [comment]
I'm going through issues and with this one, and 1.  I'm not sure if I fully understand it, and 2. I'm sure that I don't understand what this mode would be useful for. Could you maybe elaborate further?
