### ISSUE TITLE
Rename Mapping Navigator

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#496]
"Mapping Navigator" was never really intended to be the final name and it doesn't express what it actually does. We need a new name, but a good, expressive name is hard to find.

**Comment by nichtich** [comment]
How about (something with) "Connections"? The tabs could be "Concordances", "Search", and "Connections".

**Comment by stefandesu** [comment]
I don't think "Connections" is the right word, although it is a better fit than "Navigator". But right now I can't think of a better word...

**Comment by nichtich** [comment]
Just renaming won't solve the issue. Uma and me thought about separating the groups "Mappings" and "Recommendations" into tabs. Recommendations could also be shown as lists (#239). Anyway keep it as it is unless it is more clear how to improve the component.
