### ISSUE TITLE
Support configuration of fixed source scheme

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#499]
For mapping from one selected concept scheme, e.g. DDC or Wikidata it is better to set up a dedicated Cocoda instance with a fixed fromScheme. This scheme should always be selected by default and not cleare-able.

* [ ] add optional config fields `leftSchemes` and `rightSchemes` with an array of scheme uris to be listed on each side (in contrast to *all* schemes available)
* [ ] if the list contains only one scheme, directly select this scheme and disable scheme selection ("clear scheme"...) on this side

**Comment by stefandesu** [comment]
I thought a little bit about this. I feel like this only makes sense if we subsequently make sure that there will be no mappings or recommendations with an "invalid" source scheme, and this would need some deeper changes. I expect that there are further considerations as well that we haven't thought about yet.

**Comment by stefandesu** [comment]
I'm just wondering if we need this AND #490 which is kind of similar (but different). What do you think?

**Comment by nichtich** [comment]
Needs further discussion, better with a whiteboard and pencil. The comment at #490 was:

> To simplify usage with less distraction add a mode to only respect favorite concept schemes. This means:

> don't allow to select a concept scheme that is not a favorite concept schemes (or automatically make it a favorite if not possible otherwise) only show concordances between any of the favorite concept schemes (in concordance browser and mapping search) empty source/target scheme in mapping search will use union of favorite concept schemes instead of all available concept schemes in mapping navigator only show mappings between any of the favorite concept schemes

> A difficult question is how/where to enable/disable this mode.
