### ISSUE TITLE
Remove registryGroups, use hard coded groups (databases vs. recommendations) instead

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#500]
Continuation of #496: The purpose of Mapping Navigator in contrast to Mapping Search is not easy to grasp, neither its subdivision into "Mappings" and "Recommendations". Maybe use the `registryGroups` in individual tabs? This needs some discussion.

**Comment by nichtich** [comment]
We don't need specific `registryGroups` but a clear separation between databases and recommendations.

**Comment by stefandesu** [comment]
> We don't need specific `registryGroups` but a clear separation between databases and recommendations.

Isn't that exactly what `registryGroups` are for? To have a separation between databases (i.e. mappings) and recommendations? Not sure what you mean by "hard coded groups" other that what we're doing already which are hard-coded groups. 🤔

Edit: Well I guess you could override the `registryGroups` in config, so you mean that we just have the two options and each registry has to belong to one of them?

**Comment by nichtich** [comment]
> Edit: Well I guess you could override the registryGroups in config, so you mean that we just have the two options and each registry has to belong to one of them?

Yes: remove the whole configuration and only specify which registries are used to store mappings (=MappingRegistries aka "databases" in contrast to other data sources).

**Comment by stefandesu** [comment]
Okay. How would you specify this, still using the `subject` field?

**Comment by stefandesu** [comment]
> Okay. How would you specify this, still using the `subject` field?

@nichtich Could you answer this? I'd like to implement this today or tomorrow.

Also, this means that we don't need a list of `registryGroups` anymore at all, right? So we don't hardcode the `registryGroups`, but instead decide how to differentiate mapping databases from other mapping sources.

**Comment by nichtich** [comment]
We don't need `registryGroups` anymore. I thought the group could be determined automatically via the provider (e.g. OpenRefine API is always a recommendation) but better use the existing `subject` field - it's not very beautiful but explicit.

**Comment by stefandesu** [comment]
So should we use the same content for `subject` as we're using now, or can we change it in a way that 1. it is shorter (doesn't use the full http URI) and 2. maybe only needs to be defined on databases (and everything that's not a database is implied a recommendation)?

**Comment by nichtich** [comment]
The best wording I could find so far is to add a field `stored` with boolean value. If `stored` is `true`, the registry is a database, otherwise it provides recommendation which may be generated on-the-fly. Sensible default value of `stored` can be derived from other registry fields, e.g. `provider`.

**Comment by stefandesu** [comment]
- provider `LocalMappings` = stored
- provider `MappingsApi` = stored (default), but can be not stored as well (e.g. ccmapper) so that has to be specified
- provider `SearchSuggestion` = not stored
- provider `OccurrencesApi` = not stored
- provider `ReconciliationApi` = not stored

So it's clear except for `MappingsApi` although even ccmapper recommendations are in theory "stored" in the database.

We could also add a check for an additional field, e.g. check if string "recommendations" appears in the `uri` field. Seeing that there's only a single exception makes me not want to add an additional field for this.

**Comment by stefandesu** [comment]
This was now implemented. There were more changes necessary than I expected, so the dev instances ([dev](https://coli-conc.gbv.de/cocoda/dev/), [rvk](https://coli-conc.gbv.de/cocoda/rvk/), [wikidata](https://coli-conc.gbv.de/cocoda/wikidata/)) have to be tested thoroughly (keep a lookout on the console for suspicious error messages).

**Comment by stefandesu** [comment]
I couldn't find any issues in the dev instances, so I'm closing this issue. 👍
