### ISSUE TITLE
Hide "Top Concepts" tab on "No top concepts"

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#502]
If top concepts are not supported, don't show the corresponding tab.

**Comment by stefandesu** [comment]
I agree in general, but I feel like there should be some kind of indication that there are no top concepts so that it is not conceived as a bug.

**Comment by nichtich** [comment]
Several reasons may result in no top concepts: wrong configuration, bug in the server/database, bug in cocoda, scheme has no top concepts... Having an indicator that shows some of the reasons don't apply looks more like a developer functionality than something that's of use to users.

**Comment by stefandesu** [comment]
Hmm okay. I'm not convinced, but we can do that for now.

**Comment by stefandesu** [comment]
Now empty lists (except for favorite concepts because you can drag into it to add concepts to it) are hidden.
