### ISSUE TITLE
TheSettings: hide Mapping Registry dropdown if less than two entries

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#503]
If there is only one Mapping Registry available (e.g. <https://coli-conc.gbv.de/cocoda/rvk/>), don't show a dropdown at all. This may be solved together with #305.

**Comment by stefandesu** [comment]
I think #305 is something completely different. It makes sense to hide the dropdown if there is only one entry.

**Comment by nichtich** [comment]
The dropdown has another bug as it only includes writeable mapping registries but others can be selected in the mapping search. Try this: don't log in, select Wikidata and then open settings. The dropdown only contains local. Better show a list (instead of dropdown) of all available mapping registries and include the write-icon when it is writeable.

**Comment by stefandesu** [comment]
That's true. If we put a full list of all mapping registries here, isn't that kind of redundant with the "Data Sources" tab though? Or should this be a simple list (just the notation and name and whether it is writable) and more details are available under Data Sources?

**Comment by nichtich** [comment]
I'm unsure on the one hand it's better to have the selection at "Data Sources" only, so the "Account" tab is about user profile only. On the other hand the selected mapping registry comes with additional rights information (may I write mappings, confirm mappings etc.) which also fit at "Account".

**Comment by stefandesu** [comment]
For now, I completely removed it from "Account" and adjusted "Data Sources" so that Mapping Registries are at the top and can be selected for writing. Do you think this is alright? Further adjustments to "Data Sources" will be made for #305.

**Comment by nichtich** [comment]
Ok, I further worked on it, simplifying the interface.
