### ISSUE TITLE
Limit concept lists to selected concept schemes

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#507]
If a concept lists contain concepts from one or a limited number of concept schemes only, the list should only be shown at a side where one of this concept schemes is selected. The concept schemes could be specified by field `schemes` of a list:

~~~
"schemes": [{"uri": "uri-of-scheme"}]
~~~

**Comment by stefandesu** [comment]
Yeah, I've been thinking about this as well and it totally makes sense. We might also be able to remove the `inScheme` property of concepts by assuming it from the `schemes` property if there is only a single scheme, what do you think?

**Comment by nichtich** [comment]
Yes, we can infere `inScheme` from the first element of `schemes` in the case of concept lists.

**Comment by stefandesu** [comment]
I added the functionality and also updated the list at https://coli-conc.gbv.de/lists/rvk-ohne-bk-top250.json. 👍
