### ISSUE TITLE
Retrieve concept lists via API

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#508]
Field `concepts` of a concept list (which is also a [JSKOS Registry](https://gbv.github.io/jskos/jskos.html#registries) could also be allowed to JSKOS API calls that return an array of concepts:

~~~
{
  "prefLabel": { "en": "recently changed concepts" },
  "concepts": "http://example.org/api/concepts?sort=modified"
}
~~~

We first need to know which kinds of lists / queries are most likely to be useful.

**Comment by stefandesu** [comment]
Sounds reasonable. 👍
