### ISSUE TITLE
Don't assume that a mapping registry to save mappings exists

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#515]
If there is no mapping registry in which to save mappings, the application will be very buggy because there are multiple locations in the code where it is assumed that the getter for the current mapping registry does not return `null`. It should instead consider the case that there is no registry in which to save mappings at all. Also, Mapping Editor does not need to be shown in this case, as well as all buttons related to editing/saving mappings in Mapping Browser.

This came out of #514.

**Comment by nichtich** [comment]
We could also allow to disable the currently selected registry so no registry is selected for writing.

**Comment by stefandesu** [comment]
> We could also allow to disable the currently selected registry so no registry is selected for writing.

Would there be a specific use case for this? Not that I disagree, just trying to play devil's advocate.

**Comment by stefandesu** [comment]
Done with some recently changes.
