### ISSUE TITLE
MappingEditor: Move message into toolbar

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#519]
The message shown in the MappingEditor should be put together with icons etc. in a toolbar at the bottom:

![image](https://user-images.githubusercontent.com/299856/68584371-b0b17900-047f-11ea-95d9-3a9c550c2575.png)

Possible add background color to the whole toolbar. The header row could contain concept scheme names left and right and "type" in the middle to make the type more visible.

**Comment by stefandesu** [comment]
Good idea to utilize the free space after removing the comments. I don't think I would add a background color.

I guess adding "type" to the header row would help with discoverability of the mapping type, but I don't think it's a good solution to be honest. But I can't think of anything better at the moment either.
