### ISSUE TITLE
Add "my data" tab TheSettings

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#520]
TheSettings should contain a tab that gives an overview of all data authored by the logged-in in user:

* mappings (could be a link to the mapping search), separated by registry
* annotations (we don't have search and browse by annotations yet)
* link to user data at login-server

Wikidata registry does not support search by author (could be implemented), we can provide a link to the corresponding search in Wikidata instead.

**Comment by nichtich** [comment]
> annotations (we don't have search and browse by annotations yet)

A link to an API result should be enough for this issue. The point is to give a starting point to search for data created by the user, not to provide a full user interface to all of this data.

**Comment by stefandesu** [comment]
Suggestion: Rename the "Local Mappings" tab in Settings to "My Data". In there, the biggest part is "Local Mappings" with all the previous stuff (maybe better organized) and then another section with a bunch of API links for stuff that the user created. This would need to be shown for all registries the user can write into, if it's possible to filter by creator (Wikidata doesn't allow that, so we can't show it there).

**Comment by stefandesu** [comment]
I think this is good now as a first implementation. In the future, we should improve this.
