### ISSUE TITLE
User manual not accessible on dev

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#525]
It seems to work on GitHub Pages and on the release version, but not on the dev version: https://coli-conc.gbv.de/cocoda/dev/user-manual-en.html

I suspect the build on our server fails to create the manual. The release version is taken from the bundle that Travis creates, so it doesn't rely on local dependencies.

**Comment by nichtich** [comment]
It worked after installation of newest Pandoc at esx-206.
