### ISSUE TITLE
Update English user manual

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#527]
The English user manual, compared to the German version, is outdated. We should at least provide a shortened but updated version.

**Comment by stefandesu** [comment]
When I implemented the alert for #548, I noticed that while the German version is newer and more concise, I found the English version, at least in regard to the login process, much more helpful. We should definitely work on both versions of the manual.

**Comment by stefandesu** [comment]
The English version was adapted to the updated German version. It is not perfect, but good enough for now.
