### ISSUE TITLE
Concept Search filter by type should not be shown at BK

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#534]
The GND concept type filter is also shown at BK (https://coli-conc.gbv.de/cocoda/dev/). Maybe this is a misconfiguration.

**Comment by stefandesu** [comment]
We're getting BK from DANTE, and DANTE's types don't seem to be defined per scheme: https://api.dante.gbv.de/types

That endpoint is not yet documented in DANTE's documentation, and using the `uri` parameter for the scheme URI did not change the results. Is there any vocabulary in DANTE right now where we need the types? If not, we could remove the `types` property for DANTE in the config.

**Comment by stefandesu** [comment]
@nichtich ? After this is dealt with, I would suggest to release version 1.3.0.
