### ISSUE TITLE
Refactor API requests and background activity

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#536]
There seem to be many unnecessary API requests, possibly slowing down the application. This needs to be refactored.

**Comment by stefandesu** [comment]
Also look at [axios interceptors](https://github.com/axios/axios#interceptors).

**Comment by stefandesu** [comment]
How about we add one class/module/helper object or something that deals with ALL network-related activities, including background polling and timers (#509) as well as error handling (#437)? It should take advantage of async/await and we can make sure that, for example, doing the same request twice in a row does not result in two separate network requests (instead, the second one should return the promise from the first request).

**Comment by nichtich** [comment]
Ok, if such a network-proxy-object does not add more complexity. I'm unsure, so you decide.

**Comment by stefandesu** [comment]
Here are two helpful articles (more as a note for myself): 

- https://dev.to/localeai/architecting-http-clients-in-vue-js-applications-for-effective-network-communication-1eec
- https://medium.com/canariasjs/vue-api-calls-in-a-smart-way-8d521812c322

**Comment by stefandesu** [comment]
Since we are bundling all network requests into [cocoda-sdk](https://github.com/gbv/cocoda-sdk), I will close this issue here.

I also just implemented [handling multiple identical requests](https://github.com/gbv/cocoda-sdk/issues/13) in cocoda-sdk.
