### ISSUE TITLE
Configure autoRefresh for mappings in Cocoda, not per registry

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#556]
Currently, each mapping registry can have the property `autoRefresh`. This shouldn't be defined inside each registry, but rather for all mapping registries. Also, the user should be able to disabled auto refresh.

**Comment by stefandesu** [comment]
@nichtich What do you think, should auto refresh be configured for the Cocoda instance or as a user setting? Right now, I set it to 10 seconds for registries with stored mappings, but I think it should either by configurable or in the settings.

**Comment by nichtich** [comment]
Time in seconds should be configurable per Cocoda instance but users should be able to disable auto-refresh.

**Comment by stefandesu** [comment]
This is now configurable in config (with default values in `cocoda.default.json`) with a possible override from the user in MappingBrowser settings.
