### ISSUE TITLE
Is support for Node.js 8 necessary?

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#557]
Version 8's LTS maintenance cycle expired at the end of 2019 and more and more packages remove support for version 8. Is it really necessary to support it when we're already at version 14? Why would someone still use Node.js 8? @nichtich

**Comment by stefandesu** [comment]
Just to make a point: v10 just moved into maintenance and the current active LTS is v12. See: https://nodejs.org/en/about/releases/

**Comment by nichtich** [comment]
I'd look at [Ubuntu LTS releases](https://wiki.ubuntu.com/Releases) and their standard node version. Ubuntu 18.04 has node 8.10 and Ubuntu 20.04 has node 10.15, so upgrading to node 10 would be fine during this summer.

**Comment by stefandesu** [comment]
More and more packages are dropping Node.js 8 support (makes sense because it's not been supported anymore for over 6 months now), and it feels like every time I update dependencies, I run into an issue because we're still holding on to v8. Just stating this as another reason to finally drop v8 support in our next minor release.

**Comment by nichtich** [comment]
OK, drop 8.
