### ISSUE TITLE
MappingBrowser: support database selection for occurrences

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#56]
* [ ] show database of each occurence (is included in field `database`), for instance as hover at the count.
* [ ] show selected database (http://uri.gbv.de/database/opac-gvk by default)
* [ ] send database URI with parameter `database`. Example query:
http://coli-conc.gbv.de/occurrences/api?members=http://uri.gbv.de/terminology/bk/77.53&database=http://uri.gbv.de/database/opac-de-7
* [ ] select database via http://uri.gbv.de/database/api/dbkey?id={suggest} (see http://uri.gbv.de/database/ search box right above).

**Comment by stefandesu** [comment]
Needs changes in [occurrences-api](https://github.com/gbv/occurrences-api).

**Comment by stefandesu** [comment]
Should be taken into account for https://github.com/gbv/occurrences-server.

**Comment by nichtich** [comment]
Just showing the current name is enough: #711
