### ISSUE TITLE
Opening Configuration from menu should open the selected tab

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#562]
Open the configuration via one of its menu items, e.g. "User Interface" should open the corresponding tab but the settings modal is always opened with the "Account" tab.

**Comment by stefandesu** [comment]
Yeah, I noticed this as well. Should be an easy fix.

**Comment by stefandesu** [comment]
I also fixed the issue that local mappings were shown as an option in the dropdown even when it's not available.
