### ISSUE TITLE
Support enabling/disabling display of mapping registries in settings

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#563]
The "data sources" settings tab lists mapping databases and allows to select which is being written to but it does not allow to enabling/disabling whether they are shown in mapping search and navigator. It should be possible to select/deselect mapping databases. How about a checkbox in front of each database?

**Comment by stefandesu** [comment]
So what you would like is that the checkbox does the same think as deselecting it in MappingBrowser, right? That should be no problem to add.

We once had another idea that you could completely disable certain sources, but that's a different issue I think.

**Comment by stefandesu** [comment]
@nichtich Can you take a look in dev if this is okay?

**Comment by stefandesu** [comment]
I'll close this issue, please comment for smaller changes.
