### ISSUE TITLE
Add icon to deselect a concept

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#564]
Concept schemes can be deselected with the circled x icon ( ⓧ ). To deselect a concept it requires to click on the concept scheme, this is not intuitive. We should add a ⓧ on the concept as well.

**Comment by stefandesu** [comment]
Should be as simple as [reversing this commit](https://github.com/gbv/cocoda/commit/ac05d657f36dbddeebaca22c2f972e74fb8f2858). ;)

**Comment by stefandesu** [comment]
Oops, I messed up the commit message. 🤷‍♂️
