### ISSUE TITLE
Support selecting concept types

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#57]
Some vocabularies group their concepts into concept types - see for instance "Entitätentypen" at <http://gnd.eurospider.com/> for GND and table vs. class entries for DDC. RVK classes should also get types for instance to sort out classes about particular authors.

This feature requires an additional endpoint for suggest services to return a list of types. Types could also be hard-coded in config, e.g. for <https://ws.gbv.de/suggest/gnd/>:

~~~json
{
    "voc": [ {
      "uri": "http://bartoc.org/en/node/430",
      "prefLabel": { "de": "Gemeinsame Normdatei" },
      "notation": ["GND"]
    } ],
    "data": "http://coli-conc.gbv.de/services/gnd.php",
    "suggest": "https://ws.gbv.de/suggest/gnd/?searchterm={searchTerms}&type={type}",
    "types":[
  {
    "uri": "http://d-nb.info/standards/elementset/gnd#DifferentiatedPerson",
    "prefLabel": {
      "de": "Person",
      "en": "person"
    }
  },
  {
    "uri": "http://d-nb.info/standards/elementset/gnd#PlaceOrGeographicName",
    "prefLabel": {
      "de": "Geografikum",
      "en": "place"
    }
  },
  {
    "uri": "http://d-nb.info/standards/elementset/gnd#CorporateBody",
    "prefLabel": {
      "de": "Organisation",
      "en": "organization"
    }
  },
  {
    "uri": "http://d-nb.info/standards/elementset/gnd#SubjectHeading",
    "prefLabel": {
      "de": "Sachbegriff",
      "en": "subject"
    }
  }
]
}
~~~

**Comment by StiftungAusNachlass** [comment]
I added https://ws.gbv.de/suggest/gnd/types
The list is hardcoded.. We could add the list for exact_types too, if you need it.

**Comment by nichtich** [comment]
Practical mapping against GND is impossible without this feature, so better implement it earlier.

**Comment by nichtich** [comment]
See <http://blog.lobid.org/2018/03/20/gnd-class-hierarchy.html> for a more detailed classification of GND concept types, including occurrence counts.

**Comment by nichtich** [comment]
DANTE requires extension to accept for instance

https://ws.gbv.de/suggest/gnd/?searchterm=Helms&type=http%3A%2F%2Fd-nb.info%2Fstandards%2Felementset%2Fgnd%23CorporateBody%7Chttp%3A%2F%2Fd-nb.info%2Fstandards%2Felementset%2Fgnd%23SubjectHeading&count=10

equivalent to

https://ws.gbv.de/suggest/gnd/?searchterm=Helms&type=CorporateBody,SubjectHeading&count=10

**Comment by StiftungAusNachlass** [comment]
Thanks for the extended description of the requirements. The service already understood the type-parameter by URI, but only with delimiter ',' and not by '|'. I've added the pipe as delimiterchar and now the calls are working.

**Comment by stefandesu** [comment]
The first version of this is now implemented. If concept types are available (currently only for GND), they are shown in ItemDetail when the concept scheme is chosen. There, you can choose which types are used in ConceptSearch. 

SchemeDetail might not be the right place for this though. Also, right now it's not clear that the selection will influence the search results because there is no explanation. On top of that, the feature needs to be tested (it worked for the examples at least).

**Comment by stefandesu** [comment]
d0de981189c05a174651d4920ee72040d572758e moved the filter from SchemeDetail into ConceptSearch which is a much better place.
