### ISSUE TITLE
RegistryInfo: Show more accurate authentication status for registries

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#572]
Current, it shows "authenticated" or "authentication required" only for creating mappings. First of all, we have way more fine-grained permissions now, so this should be extended. But also, this is applied even to registries without mappings (which does not make any sense). I guess this is some leftover code from when authentication was only necessary for creating mappings.

@nichtich Do you have any suggestions how to display these fine-grained authentication details?

**Comment by stefandesu** [comment]
Suggestion: Show it similarly like now, only with three options (authenticated, partly authenticated, not authenticated) and show the details on mouseover (could basically be a table with each entity type as a row and the CRUD actions as columns; then for each cell, show either "yes", "own", or "no").

**Comment by nichtich** [comment]
This has been implemented in "Data Sources" view of settings.
