### ISSUE TITLE
MSC 2020

### ISSUE THREAD

**Issue by runnwerth** [gbv/cocoda#580]
Dear all,
would you please include MSC 2020?
Thank you,
Mila

**Comment by nichtich** [comment]
Sorry for the delay, [here you go with MSC2020](https://coli-conc.gbv.de/cocoda/app/?fromScheme=http%3A%2F%2Furi.gbv.de%2Fterminology%2Fmsc2020%2F)!

The [concordance between MSC2010 and MSC2020](https://mathscinet.ams.org/msc/conv.html?from=2010) is not included. If you provide it as CSV, we can import as well.

What's your use case?
