### ISSUE TITLE
ConceptScheme Detail should not show creator

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#600]
creator the one who created the record. Use publisher for display instead. Requires analysis of existing schemes data (kos-registry?).

**Comment by stefandesu** [comment]
Currently, `publisher` is shown if it exists, otherwise it will show `creator`. Is that okay or should it always be `publisher`?

**Comment by nichtich** [comment]
Better never show `creator` of a vocabulary because this data is filled with creator of the BARTOC record instead of creator of the actual vocabulary.
