### ISSUE TITLE
Add Wikidata Terminology

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#61]
Before client side Wikidata wrapper exists (#41), the following server side wrapper can be used:

~~~json
    {
      "voc": [ {
        "uri": "http://bartoc.org/en/node/1940",
        "prefLabel": { "de": "Wikidata", "en": "Wikidata" }
      } ],
      "data": "//coli-conc.gbv.de/services/wikidata.php",
      "suggest": "//coli-conc.gbv.de/services/wikidata-suggest.php?search={searchTerms}"
    }
~~~

This does not work in the current dev-version for unknown reason.

**Comment by stefandesu** [comment]
There seems to be a bug in the data service: http://coli-conc.gbv.de/services/wikidata.php?uri=http://www.wikidata.org/entity/Q188522 returns error 500. Changing the URI slightly returns an empty array.

Edit: Fixed - https://github.com/gbv/coli-conc.gbv.de/issues/11.

Edit 2: Right now, every terminology provider needs a notation. This is definitely a bug and needs to be fixed separately. For now, I will add the notation "Wikidata" to the provider.
