### ISSUE TITLE
Support Destatis: Fächergruppen, Studienbereiche und Studienfächer

### ISSUE THREAD

**Issue by TobiasNx** [gbv/cocoda#616]
Would be nice if you could support:
https://www.destatis.de/DE/Methoden/Klassifikationen/Bildung/studenten-pruefungsstatistik.pdf

Also see:
https://github.com/dini-ag-kim/hochschulfaechersystematik
https://skohub.io/dini-ag-kim/hochschulfaechersystematik/heads/master/w3id.org/kim/hochschulfaechersystematik/scheme.de.html

**Comment by stefandesu** [comment]
In theory, we already support this: https://coli-conc.gbv.de/cocoda/app/?fromScheme=http%3A%2F%2Fbartoc.org%2Fen%2Fnode%2F18920

However, it seems like something went wrong with the conversion, or we have an old version. @nichtich could you take a look?

**Comment by TobiasNx** [comment]
There are unfortunately two different Destatis Fächerklassifikationen. One concerning the students and one concerning faculty. The one you have is the faculty related vocabulary: https://www.destatis.de/DE/Methoden/Klassifikationen/Bildung/personal-stellenstatistik.pdf;jsessionid=904B75E3220D063D983FD868252FA739.live712?__blob=publicationFile

**Comment by stefandesu** [comment]
Thanks for the info! We'll look into this, I'm sure we can add the other one as well. 👍

**Comment by nichtich** [comment]
We have converted http://bartoc.org/en/node/18920 but you want http://bartoc.org/en/node/18919, already available via Skohub. We need to implement https://github.com/gbv/jskos-providers/issues/8 first.

**Comment by nichtich** [comment]
This has been implemented, see https://coli-conc.gbv.de/cocoda/dev/?fromScheme=http%3A%2F%2Fbartoc.org%2Fen%2Fnode%2F18919
