### ISSUE TITLE
Show license for non-free terminologies

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#62]
DDC translations are licensed under CC-BY-NC-ND (e.g. <https://deweysearchde.pansoft.de/> and <https://deweysearchno.pansoft.de/>). This is a very restrictive license but we might show the DDC unchanged nevertheless and we would not be the first (see <http://data.ub.uio.no/skosmos/ddc/en/> and <http://vocab.phaidra.org/skosmos/dewey/de/> top levels only). The license for German DDC is http://creativecommons.org/licenses/by-nc-nd/3.0/. Free terminologies use http://creativecommons.org/publicdomain/zero/1.0/. We can hard-code and include badges of known licenses to show:

* https://mirrors.creativecommons.org/presskit/buttons/80x15/svg/by-nc.svg
* https://mirrors.creativecommons.org/presskit/buttons/80x15/svg/cc-zero.svg

**Comment by stefandesu** [comment]
CC BY-NC-ND requires attribution. How should we integrate that into the JSKOS format and into Cocoda?

**Comment by nichtich** [comment]
In short we need to make sure that all items with CC-BY-* licenses have a creator or publisher field to show (creator if given, publisher otherwise). For DDC this would be:

~~~json
{
  "uri": "http://d-nb.info/gnd/1086052218",
  "prefLabel": { "de": "OCLC" },
  "altLabel": { "de": ["OCLC Online Computer Library Center"],
  "url": "https://www.oclc.org/"
}
~~~
