### ISSUE TITLE
WebDewey search links don't always work correctly

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#627]
It seems like we can't easily build a search link for WebDewey that works for every DDC notation. At the moment, neither notations with ranges nor `:` notations work correctly.

For example, the notation `636.1-636.8` will get the following search link: https://deweyde.pansoft.de/webdewey/index_11.html?recordId=ddc%3a636.1-636.8

However, the correct search link is this: https://deweyde.pansoft.de/webdewey/index_11.html?recordId=ddc%3a636.1-.8

It is not possible to simply construct the search link from the notation. Not sure how we should implement this properly since search links are part of the (JSON-only) configuration. @nichtich What do you think?

**Comment by stefandesu** [comment]
Maybe related to #565? It would be nice if we could use regular expressions to fix this issue without using any code, just using normal JSON strings.

**Comment by nichtich** [comment]
Looks like WebDewey search links cannot be constructed by simple URL patterns so a more complex mapping function is needed to build URL. Three ideas:

1.) implement the URL building function in Cocoda
2.) add the pre-build URLs to JSKOS data of DDC
3.) create a web service that returns search links
 
From a theoretical standpoint I'd prefer (3) actually [we had a similar websevice](https://verbundwiki.gbv.de/display/VZG/SeeAlso+Simple+Specification) to return links related to a given resource but adding just another special case for DDC in Cocoda (2) might be ok as well.

In any case also to prepare #565 it would be best to create a promise function that maps:

* a JSKOS concept with URI, notation, and inScheme
* to a list of search links, each with prefLabel and url

So the list of search links could come from a web service (e.g. as part of BARTOC) or based on URL patterns (current config) or custom rules (like WebDewey). The promise function to get search links might fit into jskos-tools.

**Comment by stefandesu** [comment]
On the one hand, I feel like Cocoda is already doing so much via HTTP requests that we should try to minimize adding new ones. On the other hand, it would make a lot of sense moving search links to an API or at least add the option of getting search links from an API. I think it's important to keep the "local" functionality so that Cocoda is not always dependent on yet another service.

I think using OpenSearch Suggest Format is a great idea.

**Comment by nichtich** [comment]
The implementation of search links provider could be used in Cocoda (executed client side) and BARTOC (executed server side) as well.

**Comment by stefandesu** [comment]
I adjusted the search link implementation and implemented the special case for DDC WebDewey. I tried all kinds of notations, so it should work now. Search links via a web service will be done later in #565.
