### ISSUE TITLE
Move favorite schemes to configuration file

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#63]
The configuration file should have a list of URIs for favorite schemes. Therefore it could be easily overwritten by someone who needs a different set of favorite schemes.

**Comment by nichtich** [comment]
In addition this could be overridden by user settings once we have these

Am 20. Juni 2018 15:50:17 MESZ schrieb Stefan Peters <notifications@github.com>:
>The configuration file should have a list of URIs for favorite schemes.
>Therefore it could be easily overwritten by someone who needs a
>different set of favorite schemes.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gbv/cocoda/issues/63

-- 
Jakob Voß via Android

**Comment by stefandesu** [comment]
That's exactly what I meant. ;) I'll do this today.
