### ISSUE TITLE
MappingEditor: Name of registry is not translated

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#637]
The registry name will not be translated to selected user interace language or the data to display name is not fully available. 

<https://github.com/gbv/cocoda/blob/49919492f7f275339d550c9e18178b14bde18ab0/src/components/MappingEditor.vue#L10> 

![image](https://user-images.githubusercontent.com/299856/140748301-b33235f9-ad0e-45cb-9725-5dd8cace6863.png)

I'd prefer to also include the Icon (here: [C]) at this place in MappingEditor.

**Comment by stefandesu** [comment]
Please check the change in Dev and close the issue if it's okay like this. 👍
