### ISSUE TITLE
Adjust config format with JSKOS specification

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#64]
The https://gbv.github.io/jskos/jskos.html#registries for the current draft of "Registries" in JSKOS. We can rename in `terminologyProviders`: `data` to `concepts` and `voc` to `schemes`. The `url` field may be renamed to `endpoint` but this needs further discussion and examples.

The content of `mappingProviders` and `occurrenceProviders` may also be modified later, e.g.

~~~ json
{
  "mappingProviders": [
    { "mappings": "//coli-conc.gbv.de/api/mappings/" }
  ],
  "occurrenceProviders": [
    { "occurrences": "//coli-conc.gbv.de/occurrences/api/" }
  ]
}
~~~

Field `occurrences` is not included in JSKOS specification for registries yet.

Open question: name "Registry" or "Provider"?

**Comment by stefandesu** [comment]
I would suggest using "Registry" as specified in JSKOS (to make it consistent). I would also propose that there is actually no need to differentiate between terminology registries, mapping registries, and occurrence registries. It would be enough to have one config field "registries" which contains all the different ones in JSKOS format and Cocoda can decide which ones to use in which situation based on the available properties.

**Comment by nichtich** [comment]
Suggested part of a config file to merge `mappingProviders`, `occurrenceProviders`, and part of `terminologyProviders`:

~~~json
{
  "registries": [
    {       
      "mappings": "//coli-conc.gbv.de/api/mappings/",
      "prefLabel": { "en": "Mapping Database" } 
    }, {
      "occurrences": "//coli-conc.gbv.de/occurrences/api/",
      "notation": ["O"],
      "prefLabel": { "en": "Occurrences", "de": "Vorkommen" }
    }, {       
      "mappings": "//example.org/mappings",
      "occurrences": "//example.org/occurrences",
      "prefLabel": { "en": "Example" },
      "notation": ["E"]
    },{
      "schemes": [ {
        "uri": "http://bartoc.org/en/node/430",
        "prefLabel": { "de": "Gemeinsame Normdatei" },
        "notation": ["GND"]
      } ],
      "concepts": "//coli-conc.gbv.de/services/gnd.php",
      "suggestConcepts": "//ws.gbv.de/suggest/gnd/?searchterm={searchTerms}"
    }
  ]
}
~~~

**Comment by stefandesu** [comment]
I'm closing this issue as the config file format has been changed. Based on this change, #209 will be implemented.
