### ISSUE TITLE
There are potential issues if mappings are delivered in the `identifier` field

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#640]
For example, GND 4074195-3 Leukozyt (http://d-nb.info/gnd/4074195-3) delivers the Wikidata mapping in `identifier` (http://www.wikidata.org/entity/Q42395), see the API request: https://coli-conc.gbv.de/services/gnd.php?uri=http%3A%2F%2Fd-nb.info%2Fgnd%2F4074195-3

I'm not sure where exactly we should deal with this. Could there be a check that looks if a URI in `identifier` is part of another concept scheme and then removes that URI? Or should it be solved on the data side, i.e. in the wrapper or when importing data into jskos-server?

What do you think, @nichtich?

**Comment by nichtich** [comment]
I've removed the `identifier` field of GND service at esx-246:/var/www/html/services.
