### ISSUE TITLE
Don't show login information if no login server is configured

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#648]
By default no login server is configured, so the Cocoda should not mention login at all:

* there should be no dropdown menu via "Account" in the navbar (currently it's "Log in")
* Account settings should not show the message "you are not logged in"

**Comment by stefandesu** [comment]
> * there should be no dropdown menu via "Account" in the navbar (currently it's "Log in")

I kept the dropdown, but added a string "Configure a mapping identity" instead if there is no login server configured AND not URI configured. If there's a URI, that will be shown like before. (But no "Log in" button anymore.)

> * Account settings should not show the message "you are not logged in"

Removed.
