### ISSUE TITLE
MappingTable: show whether mapping belongs to a concordance

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#653]
The tabular list of mappings should include an indicator (icon) to show whether the mapping is part of a concordance. We could further provide more details on hover or a popup to directly modify the status (e.g. assign mapping to concordance via MappingTable).

**Comment by stefandesu** [comment]
This sounds like a reasonable idea and something like this would be good. However, I'm slightly concerned that there will be just too many icons there. We already have four icons now (if the mapping can be annotated), so with this we'd have five. I was first thinking about adding this to MappingDetail instead, but then it would be pretty much undiscoverable. Not sure what the best way is, maybe we can just do some trial and error once the server side and #652 are implemented.

**Comment by nichtich** [comment]
With exclamation mark at the name we already have 5 icons. Better keep this issue open for later and start with having this information in MappingDetail.

**Comment by stefandesu** [comment]
Okay. 👍 The concordance is already linked in MappingDetail, but we can easily extend it so that you're able to change the concordance as well. We should make it so that whatever we use for #652 can be reused here.

**Comment by stefandesu** [comment]
We could also, instead of adding a new icon that takes up space, add some very subtle indicator for this, like a little nook in a corner or something. I think it would be helpful to see at a glance which mappings belong to a concordance and which don't. However, with the new concordance filters ("any concordance" and "no concordance"), this might not be necessary anymore because we can just filter the set.

**Comment by nichtich** [comment]
> I think it would be helpful

Yes, but let's consider only if actual mapping practice shows that this would improve usability

> this might not be necessary anymore because we can just filter the set.

Workaround exists, we'll see whether this is enough. I'm closing this issue for now.
