### ISSUE TITLE
Don't use localized dates

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#655]
SchemeDetails card shows dates in German local format. Better use international format (YYYY-MM-DD) like in MappingTable.

![grafik](https://user-images.githubusercontent.com/299856/145984105-2548c5a8-9821-4719-8b96-8ffcc4e95073.png)

**Comment by stefandesu** [comment]
I think localized date format is nice, but I'd be fine with changing it back to ISO format. You're right that it is not consistent with MappingBrowser, but I think the reasoning was that we have limited space in MappingBrowser and with ISO dates, we know know much space it will take (10 characters), while in SchemeDetail/ConceptDetail, we have much more space.

Should we just show the date like it is saved in JSKOS, e.g. `2021-12-13T07:46:24.235Z` (if there's a time as well)? We could also make it a bit more readable and show it as `2021-12-13 07:46 (UTC)`.

**Comment by nichtich** [comment]
For both vocabularies and schemes the exact timestamp is not relevant, better show date only and timestamp on hover. We could spare space by putting all dates in one line (if needed).
