### ISSUE TITLE
Consistent search links to k10+

### ISSUE THREAD

**Issue by guitarster** [gbv/cocoda#657]
search links to k10+ at RVK and BK lead to different databases. 
Better: search links to k10+ lead to the same catalogue. I suggest opac.k10plus.de (not kxp.k10plus.de).

**Comment by stefandesu** [comment]
@nichtich I think you added the search links (or gave me the URLs to add). Is there any reason that different URLs are used? I see that the DB version is different as well (2.1 vs 2.299).

**Comment by nichtich** [comment]
>  Is there any reason that different URLs are used? I see that the DB version is different as well (2.1 vs 2.299).

Only historical reasons that don't apply anymore.
