### ISSUE TITLE
Order of JSKOS field `ancestors` not implemented correctly

### ISSUE THREAD

**Issue by guitarster** [gbv/cocoda#658]
Example: I choose 56.88 in BK on the right side. The hierachy is displayed from down to top (from "56.80 Gebäudelehre: Allgemeines" to "5 Ingenieurwissenschaften"). But it should be displayed top-down (from "5 Ingenieurwissenschaften" to "56.88 Sakralbau") as at RVK (From "ZG-ZS Technik" to "ZH 6330 Sakral- und Friedhofsanlagen").

**Comment by stefandesu** [comment]
This seems to be a bug in DANTE (the backend used for BK). Its `/ancestors` endpoint returns the ancestors in the wrong order.

**Comment by stefandesu** [comment]
Well, I consulted the [JSKOS specification](https://gbv.github.io/jskos/jskos.html) regarding the `ancestors` field and realized that we have implemented it the wrong way for all these years. Oops. Thanks for pointing this out! I need to do a lot of changes to fix this.

**Comment by stefandesu** [comment]
Fixed in [version 1.5.2](https://github.com/gbv/cocoda/releases/tag/1.5.2).
