### ISSUE TITLE
BK isn't loading; only after reloading the page (several times)

### ISSUE THREAD

**Issue by guitarster** [gbv/cocoda#659]
When opening cocoda and selecting BK, the Hierachical View isn't loaded. I must reload the page (sometimes twice) to get the Hierachical View.

**Comment by stefandesu** [comment]
Yeah, it's REALLY slow at the moment, sometimes so slow that a request takes longer than Cocoda's timeout and it will give up. I already sent a Slack message to the person responsible for DANTE regarding this and #658.

**Comment by stefandesu** [comment]
They made some changes and it should be much faster now.
