### ISSUE TITLE
Search link from RVK to k10plus searches by BK-Number

### ISSUE THREAD

**Issue by guitarster** [gbv/cocoda#660]
It should search by RVK-Number, i.e. PD 2000

**Comment by stefandesu** [comment]
If I open RVK PD 2000 on the left side and BK 86.18 on the right side ([Cocoda link](https://coli-conc.gbv.de/cocoda/app/?fromScheme=http%3A%2F%2Furi.gbv.de%2Fterminology%2Frvk%2F&toScheme=http%3A%2F%2Furi.gbv.de%2Fterminology%2Fbk%2F&from=http%3A%2F%2Frvk.uni-regensburg.de%2Fnt%2FPD%25202000&to=http%3A%2F%2Furi.gbv.de%2Fterminology%2Fbk%2F86.18)), I get https://opac.k10plus.de/DB=2.299/CLK?IKT=3002&NOABS=Y&TRM=PD%202000 as the K10plus link on the left side and https://opac.k10plus.de/DB=2.299/CMD?ACT=SRCHA&TRM=bkl+86.18 as the K10plus link on the right side, which seems correct. Is there anything I'm missing to reproduce this bug?

**Comment by guitarster** [comment]
Sorry, i checked it a second time. The links are correct.
