### ISSUE TITLE
Suchfilter: Mappings einer bestimmten Beziehung

### ISSUE THREAD

**Issue by mjanssen-gbv** [gbv/cocoda#668]
Suchfilter um Mappings einer bestimmten Beziehung anzuzeigen.

Nur narrow / exact / close / related etc.

**Comment by stefandesu** [comment]
Das geht schon. Es gibt erweiterte Filteroptionen, wenn man den Filter-Button rechts von "Search" klickt. Man könnte das noch etwas zugänglicher machen.
