### ISSUE TITLE
Numerically sort concepts by notations if configured

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#677]
`sortConcepts` allows to numerically sort concepts but this feature is not used in Cocoda yet. Whether to sort numerically depends on the vocabulary. The information should be available in JSKOS extension field `DISPLAY` where we already have `hideNotation` (also not respected in Cocoda yet). Requires <https://github.com/gbv/bartoc.org/issues/162>.

**Comment by stefandesu** [comment]
Is the `DISPLAY` extension field documented anywhere? `hideNotation` is clear (and is already set on a few vocabularies like GND), but I couldn't find any example for the sorting.

**Comment by stefandesu** [comment]
`hideNotation` is now respected. Notations are still shown when the label is not available or hidden.

**Comment by nichtich** [comment]
Could be `DISPLAY.numericalNotation` (with `false` as default)

**Comment by stefandesu** [comment]
`DISPLAY.numericalNotation` is now respected. Unfortunately, there is no vocabulary currently available to test, but it works well with a local test vocabulary.
