### ISSUE TITLE
Top Concepts of RVK are not shown in the favorites menu

### ISSUE THREAD

**Issue by guitarster** [gbv/cocoda#678]
This problem occured on Friday, 11th of March 2022.

Top Concepts of RVK are not shown in the favorites menu. The hierachical view at concepts details is ok; browsing works. But it is not possible to browse through the vocabulary in the favorites menu an select a concept for mapping. 
In BARTOC, browsing through the top concepts is also not possible. Searching for a concept works.

**Comment by stefandesu** [comment]
Just to clarify because I was extremely confused: The favorites menu has nothing to do with this. It's just what is shown when no hierarchical view is available for a vocabulary. The actual issue is: 

Top concepts for RVK are missing, but everything else seems to work.

I will look into it.

**Comment by stefandesu** [comment]
Works again now. For a long-term fix, see https://github.com/gbv/jskos-server/issues/163.
