### ISSUE TITLE
Relation type for 1-n mappings

### ISSUE THREAD

**Issue by guitarster** [gbv/cocoda#688]
Do we need a special relation type for 1-n mappings?

Currently there is no relationship type for composite mappings in Cocoda.
The thought is, if a class can be mapped  to  two or more classes in the target vocabulary, would it be better to have standalone mappings or one 1-n mapping with a special relationship type?

Comments welcome!

**Comment by nichtich** [comment]
Composite mappings have normal relation types.

> if a class can be mapped to two or more classes in the target vocabulary, would it be better to have standalone mappings or one 1-n mapping with a special relationship type?

if it can be mapped to both (OR), then better create two mappings. If it can be mapped to *the combination of both* (AND) then it must be a 1-n mapping.

**Comment by nichtich** [comment]
Question Solved!
