### ISSUE TITLE
Idea: Batch creation of mappings

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#699]
In some cases, it is necessary (or convenient) to create multiple mappings at the same time, e.g. we have 20 concepts in the source vocabulary that all map to the same target concept with the same mapping type.

I'm imagining a separate mode of creating mappings where it is possible to select X source concepts (probably via checkboxes in the hierarchy view) and allow creating X mappings from that selection. The Mapping Editor could show something like "X selected concepts" and make clear that the user is creating X mappings at the same time if they click "save".

I can create a mockup of what I think this could look like. There are still some open questions though:

- Should the mappings be somehow linked to each other so that they can be batch-edited as well?
- Should there be an "undo" button if there has been a mistake?
- Is it enough if the selection is only possible in the hierarchy view? This would restrict this functionality to mono hierarchical vocabularies, but it would also be easiest to implement.

**Comment by nichtich** [comment]
Moved to #713 with changed scope.
