### ISSUE TITLE
Create mapping table component

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#7]
A component for tabular display of a list of [mappings](https://gbv.github.io/jskos/jskos.html#concept-mappings). Several cases must be distinguished:

* table of mappings between the same two concept schemes
* table of mappings between one concept and other concepts from different concept schemes

The table will somehow need to be connected to the mapping editor component (#1) in a next step.

**Comment by stefandesu** [comment]
This is now implemented as MappingBrowser. All additional changes will be their own features/issues.
