### ISSUE TITLE
Extend popover for concept details

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda#700]
In some cases, it is useful to see additional information about a concept without having to select it. This is already possible in Mapping Browser (only shows scopeNote though, IIRC), but could also be implemented in the hierarchy view (and/or ConceptDetails) and show more information (e.g. alternative labels).

**Comment by guitarster** [comment]
I would find it also very useful to have such a mouseover at the suggestion tabs. I often use the suggestions to find classes. Currently, I have to click on a suggestion to get more Information about this concept. With a mouseover this step could be avoided.

**Comment by stefandesu** [comment]
@DavidBRohrer This is now implemented for Mapping Search and Mapping Navigator (i.e. also for the suggestions). Do you think it would also be helpful to have this popover in the hierarchy? I feel like it would be a bit too much, or at least we would need to add a longer delay to not overwhelm the user.

**Comment by guitarster** [comment]
I also think, that it would  be too much in general. I imagine only one special case where this popup would also be helpful in the hierarchy:

RVK: RB 10295. There is a note which refers to TI 7300. So when the user wants to check what TI 7300 means, he has to search for this notation (for example by browsing) an has to click on TI 7300 to see all concept details. In this case the concept details of RB 10295 disappear and it is not possible to compare both concepts in detail any more. So a popover would be very helpful here.

In RVK there are seldomly such references.
But in BK there are often such references ("siehe").
So in my opinion we should have this popup also in the hierarchy, but with a delay of ~1-2 seconds.

**Comment by guitarster** [comment]
Another point is, that without the hierarchy it is difficult to decide if a concept is really an option. For example https://coli-conc.gbv.de/cocoda/dev/?fromScheme=http%3A%2F%2Fbartoc.org%2Fen%2Fnode%2F533&toScheme=http%3A%2F%2Fbartoc.org%2Fen%2Fnode%2F18785&to=http%3A%2F%2Furi.gbv.de%2Fterminology%2Fbk%2F38.48&from=http%3A%2F%2Frvk.uni-regensburg.de%2Fnt%2FRB%252010295. 
When you are mapping the topic "Geomorphologie" in RVK you mostly chose BK notations out of 38.xx. In this example you get the proposal 57.14 Meeresbergbau. But someone who do not really know about other top-concepts of the BK, doesn't know what 57.xx stands for, so he has to scroll down the hierarchy on the right side to check.
Is it possible to add the short hierarchy as shown over the concept details in the popup?

**Comment by guitarster** [comment]
We need a delay of ~2 seconds in general. 
Wanted to select a notation, but couldn't because the popup was so huge, that it was overlapping the whole link to the concept: https://coli-conc.gbv.de/cocoda/dev/?fromScheme=http%3A%2F%2Fbartoc.org%2Fen%2Fnode%2F533&toScheme=http%3A%2F%2Fbartoc.org%2Fen%2Fnode%2F18785&from=http%3A%2F%2Frvk.uni-regensburg.de%2Fnt%2FQF

**Comment by stefandesu** [comment]
In addition to the longer delay (which I agree), we could also add a maximum popup height so that larger popups will be cut off and scrollable. Should be easy to implement.

As far as I can see, we have the following to-dos now:

- [x] Add delay of 1-2 seconds (decide based on feeling)
- [x] Add short hierarchy like in ConceptDetail
- [x] Add maximum height that large popups are scrollable and do not take up the whole screen
- ~~Add to concepts in ConceptList (full hierarchy) as well~~ -> decided to skip for now

Edit:
- [x] Data (including ancestors) need to be loaded on mouseover
- [x] Check potential issues with non-hierarchical vocabularies like GND and Wikidata

**Comment by stefandesu** [comment]
I think I need to rewrite how the popover works. Implementing it in the hierarchy is not as easy as I expected, and there are some reactivity issues with how the current popover is implemented.

Currently, the popover is implemented directly in the ItemName component. Since ConceptListItem does not use ItemName, it would need to be reimplemented there. A better way would be to have the popover functionality completely external to ItemName/ConceptListItem. I will work on this next week.

**Comment by stefandesu** [comment]
The feature has been rewritten and it seems to be working very well now. I'm currently leaning towards not adding it to the hierarchy view for now. This should be a new issue if still relevant.
