### ISSUE TITLE
Allow to edit names of concordance contributors

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#708]
Concordance contributors are edited in a simple text input field with one URI per line. This should be extended to URI, optionally followed by spaces and a name. The name should be saved as prefLabel of the contributor (probably default language `en`) so the concordance record can include contributor names.

Example input

    https://coli-conc.gbv.de/login/users/xxx Darth Vader
    https://coli-conc.gbv.de/login/users/yyy

JSON:

~~~json
[
  { "uri": "https://coli-conc.gbv.de/login/users/xxx", "prefLabel": { "en": "Darth Vader" } },
  { "uri": "https://coli-conc.gbv.de/login/users/yyy"  }
]
~~~

**Comment by stefandesu** [comment]
Now implemented in Dev, exactly liked described above (only that any number of whitespace can separate URI and name; it was a regex anyway).

There's an issue in jskos-server that does not allow removing names from concordances via PATCH. This is separate from this issue though.

**Comment by stefandesu** [comment]
The jskos-server issue will be fixed in the upcoming v2 release.
