### ISSUE TITLE
Highlight "same" mappings

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#73]
Mapping Browser highlights a row if it contains a mapping between selected concepts from both sides (light blue). This highlighting should be removed. Instead highlight based on same combinations of mapping member concept URIs (this requires a new feature to identify mappings to be specified!). Highlight when hovering mappings in Mapping Browser, Occurrences Browser and Mapping Editor so it is visible when the same mapping is shown in Mapping Browser and Occurrences.

**Comment by nichtich** [comment]
See <https://github.com/gbv/wikidata-jskos/commit/8c9d02a95a48ba42271c7bec362a3de5a5dc8874> for implementation of mapping identifier calculation.

**Comment by nichtich** [comment]
Seems to be implemented in MappingBrowser but not in OccurrencesBrowser. The latter requires https://github.com/gbv/jskos/issues/67 to add mapping identifiers to Occurences.

**Comment by stefandesu** [comment]
> Seems to be implemented in MappingBrowser but not in OccurrencesBrowser.

1. I think this was actually implemented in OccurrencesBrowser before, but apparently got lost in the transition to the new table. 

2. IIRC it was done by converting the occurrence into a mapping and then adding an identifier, but if occurrences can now "natively" have identifiers that match those of a mapping, this might not be necessary anymore.

3. This is only for selected concepts, not for "same mappings" like this issue describes. In fact, the issue text suggests that this highlight should be completely removed (which I don't agree with to be honest).

The problem with implementing this is that in the currently implementation, it would reload the whole table each time a different mapping is hovered (I think). It might be necessary to add another feature to vue-flexible-table to implement this.
