### ISSUE TITLE
Create Occurrence List component

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#8]
A list or table of [Concept Occurrences](https://gbv.github.io/jskos/jskos.html#concept-occurrences) to be shown as mapping recommendations.

**Comment by nichtich** [comment]
A basic occurrences webservice has been started for GVK and BK, for instance:
<http://coli-conc.gbv.de/concordances/occurrences.php?concepts=http://uri.gbv.de/terminology/bk/86.78>

**Comment by nichtich** [comment]
The webservice has been moved <http://coli-conc.gbv.de/occurrences/api/>, implementation at <https://github.com/gbv/occurrences-api>

**Comment by nichtich** [comment]
Can be closed as soon as co-occurrences have been implemented.

**Comment by stefandesu** [comment]
4698bebb827105621bb692a5b1d1eda44f7a8485 implements co-occurrences.
