### ISSUE TITLE
Clear scheme icon is misleading

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#89]
The "Clear scheme" icon (-) can be confused with the "minimize component" icon [-]. It may be replaced with an (x) or a ["home" icon](https://fontawesome.com/icons/home?style=solid) but three icons (i), (x), and (-) may be too much anyway, so better allow to clear scheme by other means?

**Comment by stefandesu** [comment]
As we now hide the buttons when they are not necessary (#88) and because there is no (-) icon near the scheme selection, I'd suggest to leave it like this for now. It's definitely much clearer with the new (x) icon instead of the (-).
