### ISSUE TITLE
ConceptDetails: Support adding to MappingEditor

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#91]
A hovered concept in ConceptTree shows a (+) icon to add the concept to the MappingEditor. The same icon should be shown (probably always, not only on hover) right to the concept label in ConceptDetail.

We may then get also get rid of the (+) and trashbin icons in MappingEditor

**Comment by stefandesu** [comment]
The button is now added in ConceptDetail. I'll leave the buttons in MappingEditor for now, we can talk about removing them later.
